#!/usr/bin/env python3
"""Local-model lifecycle regression checks without an App build.

Two jobs:

1. Generate `helpers_probe.swift` by *textually extracting* the real
   `boundedRuntimeDiagnostic`/`isCancellation` bodies from
   `MLXTextEngine.swift`, so source drift fails the harness instead of
   silently testing a stale copy. That probe is compiled and run by the
   runner.
2. Assert the structural invariants of the lifecycle repair directly on the
   production sources: foreground admission, register→launch ordering, the
   cancellation relay, the MLX teardown/diagnostic guards and the absence of
   dispatch/timer/signal workarounds.

Usage:
    python3 extract_and_assert.py <MLXTextEngine.swift> <out-dir> \
        <LocalInferenceBackgroundCanceller.swift> <LocalProviderAdapter.swift>

Exit 0 when every assertion passes, 1 otherwise. The runner treats exit 1 as a
FAIL, not a skip.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

FIXTURE_HEADER = """// Generated by extract_and_assert.py — do not edit by hand.
import Foundation
import Darwin

enum Extracted {
"""

PROBE_MAIN = r"""
}

func runFixtureChecks() -> Int {
    var failures: [String] = []
    var passes = 0

    func expect(_ condition: Bool, _ label: String) {
        if condition { passes += 1 } else { failures.append(label) }
    }

    struct EmptyDescriptionError: LocalizedError {
        var errorDescription: String? { "" }
    }

    // --- boundedRuntimeDiagnostic ---------------------------------------------

    let mlxError = NSError(
        domain: "MLXError",
        code: 1,
        userInfo: [NSLocalizedDescriptionKey:
            "MLX Error: [METAL] Command buffer execution failed: Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang). at mlx/backend/metal/device.cpp:544"])
    let bounded = Extracted.boundedRuntimeDiagnostic(mlxError)
    expect(bounded.contains("domain=MLXError"), "bounded keeps the error domain")
    expect(bounded.contains("code=1"), "bounded keeps the error code")
    expect(bounded.contains("Command buffer execution failed"), "bounded keeps the MLX/Metal message")
    expect(!bounded.contains("\n") && !bounded.contains("\r"), "bounded strips newlines")

    let multiline = NSError(
        domain: "FloeLocalModels.LocalInferenceError",
        code: 5,
        userInfo: [NSLocalizedDescriptionKey: "line one\nline two\r\nline three"])
    let flat = Extracted.boundedRuntimeDiagnostic(multiline)
    expect(!flat.contains("\n") && !flat.contains("\r"), "multiline failures stay single-line")

    let empty = Extracted.boundedRuntimeDiagnostic(EmptyDescriptionError())
    expect(empty.contains("<no description>"), "empty descriptions fall back to a marker")

    let long = NSError(
        domain: "MLXError",
        code: 2,
        userInfo: [NSLocalizedDescriptionKey: String(repeating: "x", count: 900)])
    let clipped = Extracted.boundedRuntimeDiagnostic(long)
    expect(clipped.contains("…"), "over-long failures are truncated")
    let messagePart = clipped.components(separatedBy: "message=").last ?? ""
    expect(messagePart.count == 241, "truncated message is bounded to 240 characters plus the ellipsis")

    let customLimit = Extracted.boundedRuntimeDiagnostic(long, limit: 10)
    expect(customLimit.contains("x…"), "custom limit is honoured")

    // --- isCancellation -------------------------------------------------------

    expect(Extracted.isCancellation(CancellationError()), "CancellationError is cancellation")
    expect(Extracted.isCancellation(NSError(domain: "Swift.CancellationError", code: 1)),
           "Swift.CancellationError domain is cancellation")
    expect(Extracted.isCancellation(URLError(.cancelled)), "URLError.cancelled is cancellation")
    expect(!Extracted.isCancellation(URLError(.timedOut)), "URLError.timedOut is not cancellation")
    expect(!Extracted.isCancellation(mlxError), "MLXError is not cancellation")
    expect(!Extracted.isCancellation(NSError(domain: "FloeLocalModels.LocalInferenceError", code: 5)),
           "decodeFailed is not cancellation")

    print("fixture checks: \(passes) passed, \(failures.count) failed")
    for failure in failures { print("FAIL: \(failure)") }
    return failures.isEmpty ? 0 : 1
}

exit(Int32(runFixtureChecks()))
"""


def extract_braced_function(text: str, marker: str) -> str:
    start = text.index(marker)
    brace = text.index("{", start)
    depth = 0
    for index in range(brace, len(text)):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                body = text[start:index + 1]
                return body.replace("nonisolated ", "")
    raise SystemExit(f"unterminated function for {marker}")


def canceller_assertions(text: str) -> list[str]:
    problems: list[str] = []
    # Comments mention the forbidden APIs too; only code is checked.
    code = "\n".join(
        line for line in text.splitlines()
        if not line.strip().startswith("//")
    )
    for marker in (
        "func registerForeground(",
        "func isForegroundEligible(",
        "func applyLifecycleTransition(isBackground:",
        "final class LocalInferenceCancellationRelay",
        "UIApplication.willResignActiveNotification",
        "UIApplication.didEnterBackgroundNotification",
        "UIApplication.didBecomeActiveNotification",
        "await MainActor.run",
    ):
        if marker not in text:
            problems.append(f"canceller missing {marker}")
    if "#if canImport(UIKit)" not in text:
        problems.append("canceller must keep the UIKit dependency platform-gated")
    if "import UIKit" in text and "#if canImport(UIKit)" not in text.split("import UIKit")[0]:
        problems.append("UIKit import must be platform-gated")
    for forbidden in ("DispatchQueue", "Timer", "Task.sleep", "Thread.sleep"):
        if forbidden in code:
            problems.append(f"canceller must stay a plain registry, found {forbidden}")
    if "func register(traceID:" in code:
        problems.append(
            "ungated synchronous register API must not return; production uses registerForeground"
        )
    return problems


def runtime_assertions(runtime_text: str) -> list[str]:
    problems: list[str] = []
    body = extract_braced_function(runtime_text, "func completeMeasured(")

    gate = body.find("await LocalInferenceBackgroundCanceller.shared.isForegroundEligible()")
    prepare = body.find("try await prepareEngine(")
    register = body.find("await LocalInferenceBackgroundCanceller.shared.registerForeground(")
    recheck = body.find(
        "try Task.checkCancellation()",
        register if register >= 0 else 0,
    )
    task = body.find("let generation = Task {")
    attach = body.find("cancellationRelay.attach(")
    handler = body.find("withTaskCancellationHandler")

    if min(gate, prepare, register, task, attach, handler) < 0:
        problems.append("completeMeasured is missing a lifecycle-ordering marker")
    else:
        if not (gate < prepare):
            problems.append("foreground gate must run before prepareEngine maps the model")
        if not (prepare < register):
            problems.append("registration must run after the engine exists")
        if not (register < task):
            problems.append("registerForeground must precede the GPU task creation")
        if not (register < recheck < task):
            problems.append("caller cancellation must be re-checked between registration and launch")
        if not (task < attach):
            problems.append("relay attach must follow the GPU task creation")
        if not (attach < handler):
            problems.append("relay attach must precede the cancellation handler await")

    if "LocalInferenceCancellationRelay()" not in body:
        problems.append("completeMeasured must use the cancellation relay")
    if "localInferenceBackgroundCancelled" not in body:
        problems.append("background cancellation must be logged")
    if "localInferenceBackgroundRefused" not in body:
        problems.append("background admission refusal must be logged")
    if "if error is CancellationError {" not in runtime_text:
        problems.append("cancellation must not be recorded as a model load failure")
    if "DispatchQueue.main.sync" in runtime_text:
        problems.append("runtime must not block the main actor waiting for UIKit state")
    return problems


def engine_assertions(text: str) -> list[str]:
    problems: list[str] = []
    # Comments mention the APIs too; count code only.
    code = "\n".join(
        line for line in text.splitlines()
        if not line.strip().startswith("//")
    )

    def count(pattern: str, haystack: str = code) -> int:
        return len(re.findall(pattern, haystack))

    if count(r"Self\.drainMLXPipeline\(\)") != 1:
        problems.append("drainMLXPipeline must have exactly one call site (inside the scoped helper)")
    helper = extract_braced_function(text, "static func drainPipelineAndClearCaches")
    if "Self.drainMLXPipeline()" not in helper or "Memory.clearCache()" not in helper:
        problems.append("drainPipelineAndClearCaches must wrap drain + clearCache")
    if "MLX.withError" not in helper or "errors.check()" not in helper:
        problems.append("teardown helper must run under MLX.withError and check the box")
    if count(r"Memory\.clearCache\(\)") != 1:
        problems.append("every Memory.clearCache call must be inside the scoped teardown helper")

    for marker in (
        "localInferencePrefillCompleted",
        "localInferencePrefillFailed",
        "localInferenceDecodeFailed",
        "localInferencePrepareFailed",
        "localInferenceTeardownError",
    ):
        if marker not in text:
            problems.append(f"missing diagnostic marker {marker}")

    if "throw LocalInferenceError.decodeFailed" not in text:
        problems.append("decode failures must still surface as LocalInferenceError.decodeFailed")

    for forbidden in ("signal(SIG", "NSSetUncaughtExceptionHandler", "set_terminate", "SIGABRT"):
        if forbidden in text:
            problems.append(f"forbidden crash swallowing construct present: {forbidden}")

    if count(r"MLX\.withError") < 4:
        problems.append("expected scoped MLX error handling around load, prepare, generate and teardown")

    if "if Self.isCancellation(error) { throw CancellationError() }" not in text:
        problems.append("cancelled prepare must rethrow CancellationError")
    if "if Self.isCancellation(error) || Task.isCancelled { throw CancellationError() }" not in text:
        problems.append("cancelled prefill/final decode must rethrow CancellationError")
    if "if Task.isCancelled { throw CancellationError() }" not in text:
        problems.append("stream loop must honour task cancellation")

    return problems


def main() -> int:
    engine_src = pathlib.Path(sys.argv[1])
    out = pathlib.Path(sys.argv[2])
    canceller_src = pathlib.Path(sys.argv[3]) if len(sys.argv) > 3 else None
    runtime_src = pathlib.Path(sys.argv[4]) if len(sys.argv) > 4 else None
    text = engine_src.read_text()

    problems = engine_assertions(text)
    if canceller_src:
        problems += canceller_assertions(canceller_src.read_text())
    else:
        problems.append("canceller source path is required")
    if runtime_src:
        problems += runtime_assertions(runtime_src.read_text())
    else:
        problems.append("runtime source path is required")

    for problem in problems:
        print(f"STATIC FAIL: {problem}")

    bounded = extract_braced_function(text, "static func boundedRuntimeDiagnostic")
    cancellation = extract_braced_function(text, "static func isCancellation")
    probe = FIXTURE_HEADER + bounded + "\n\n" + cancellation + "\n" + PROBE_MAIN
    out.mkdir(parents=True, exist_ok=True)
    (out / "helpers_probe.swift").write_text(probe)
    print(f"wrote {out / 'helpers_probe.swift'} ({len(probe)} bytes)")

    summary = {
        "engine_source": str(engine_src),
        "canceller_source": str(canceller_src) if canceller_src else None,
        "runtime_source": str(runtime_src) if runtime_src else None,
        "static_problems": problems,
        "extracted": ["boundedRuntimeDiagnostic", "isCancellation"],
    }
    (out / "extract-summary.json").write_text(json.dumps(summary, indent=2))
    return 0 if not problems else 1


if __name__ == "__main__":
    raise SystemExit(main())
