// FloeApp — DEBUG-only qualification fixture for the real-engine cloud simulator run.
//
// SPDX-License-Identifier: MPL-2.0
#if DEBUG
import Crypto
import Foundation
import FloeNotes

/// Imports the pinned synthetic PPTX through the real Notes importer for the
/// cloud simulator qualification (`.github/workflows/office-floe-simulator.yml`).
///
/// The UI test passes the deterministic fixture bytes (generated by
/// `scripts/office_real_simulator/make_fixture.py`, pinned in
/// `scripts/office_real_simulator/sim_paths.py`) through the launch
/// environment; this plumbing decodes them, writes a temporary file and calls
/// `NoteFileImporter.importFile` — the same import path a user-driven file
/// import uses — so the Office session under test is a genuinely imported
/// Notes document, never an in-memory mock.
///
/// Gated on `-ui-testing` plus an explicit launch argument; idempotent per
/// install. It records one small receipt (`office-real-engine-import.json`)
/// in OfficeDiagnostics so the persistence gate can locate the imported
/// resource inside the app container; the durable stage trace records only
/// the fixture SHA-256 (content-free by construction).
@MainActor
enum OfficeRealEngineQualificationFixture {
    static let launchArgument = "--ui-test-office-real-engine"
    static let environmentKey = "FLOE_OFFICE_REAL_ENGINE_FIXTURE_B64"
    static let receiptName = "office-real-engine-import.json"
    static let fixtureBaseName = "floe-sim-qual.pptx"
    /// Pinned synthetic fixture (scripts/office_real_simulator/sim_paths.py).
    static let fixtureSHA256 = "4b8ab9081859526bd019323f4b08e1d109f6a4ffa5deb43b71631f3da049fff5"
    /// Container-relative Notes resources directory (NotesRepository storage root).
    static let notesResourcesRelativePath = "Library/Application Support/FloeAgent/Notes/Resources"

    static func seedIfRequested(session: NotesSession) async {
        let arguments = ProcessInfo.processInfo.arguments
        guard arguments.contains("-ui-testing"), arguments.contains(launchArgument) else { return }
        // Qualification-only: never on a real device, never in production.
        #if targetEnvironment(simulator)
        guard let encoded = ProcessInfo.processInfo.environment[environmentKey],
              let data = Data(base64Encoded: encoded), !data.isEmpty,
              let store = session.store else { return }
        let existing = (try? await store.documents(includeTrash: true)) ?? []
        guard !existing.contains(where: { $0.title == noteTitle }) else { return }

        let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
        guard digest == fixtureSHA256 else {
            // A drifted fixture must never seed a different document silently.
            OfficeStageRecorder.shared.record(session: "qualification",
                                              generation: 0,
                                              stage: "qualification.fixture.rejected",
                                              detail: ["reason": "sha256-mismatch"])
            return
        }

        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("office-real-engine-fixture-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }
        let url = root.appendingPathComponent(fixtureBaseName)
        do {
            try data.write(to: url, options: .atomic)
            let draft = try await NoteFileImporter.importFile(url, notebookID: nil, store: store)
            _ = try? await store.create(draft)
            try? await session.reload()

            var originalResourceSHA256 = ""
            if let resourceID = draft.officeResourceID,
               let resourceURL = try? await store.resourceURL(resourceID) {
                originalResourceSHA256 = resourceURL.lastPathComponent
            }
            OfficeStageRecorder.shared.record(session: "qualification",
                                              generation: 0,
                                              stage: "qualification.fixture.imported",
                                              detail: ["sha256": digest, "format": "pptx"])
            writeReceipt(documentID: draft.id, originalResourceSHA256: originalResourceSHA256,
                         fixtureSHA256: digest)
        } catch {
            OfficeStageRecorder.shared.record(session: "qualification",
                                              generation: 0,
                                              stage: "qualification.fixture.failed",
                                              detail: ["domain": (error as NSError).domain])
        }
        #endif
    }

    /// The Notes card title the UI test opens (import keeps the file basename).
    static var noteTitle: String { (fixtureBaseName as NSString).deletingPathExtension }

    private static func writeReceipt(documentID: UUID,
                                     originalResourceSHA256: String,
                                     fixtureSHA256: String) {
        guard let support = try? FileManager.default.url(for: .applicationSupportDirectory,
                                                         in: .userDomainMask,
                                                         appropriateFor: nil,
                                                         create: true) else { return }
        let directory = support.appendingPathComponent("FloeAgent/OfficeDiagnostics", isDirectory: true)
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let receipt: [String: Any] = [
            "documentID": documentID.uuidString,
            "noteTitle": noteTitle,
            "fixtureSHA256": fixtureSHA256,
            "originalResourceSHA256": originalResourceSHA256,
            "resourcesRelativePath": notesResourcesRelativePath,
            "synthetic": true,
            "userContent": false,
        ]
        guard let body = try? JSONSerialization.data(withJSONObject: receipt,
                                                     options: [.prettyPrinted, .sortedKeys]) else { return }
        try? body.write(to: directory.appendingPathComponent(receiptName), options: .atomic)
    }
}
#endif
