// FloeLocalModelCatalog — classify a failed local model container construction.
//
// SPDX-License-Identifier: MPL-2.0
//
// A "MLX container initialization failed … code 0" message told the user
// nothing: the generic engine code covers damaged weights, a missing file, an
// unsupported architecture, a tokenizer parse failure and a Metal allocation
// failure alike. The runtime checks the snapshot deterministically before
// asking MLX to load, loads the tokenizer in its own attributed stage, and
// this classifier maps the remaining failure to a user-actionable kind:
//
//   - `corruptSnapshot`      re-download the model (damaged/missing files)
//   - `insufficientMemory`   free memory / stop the Linux guest / smaller model
//   - `unknown`              keep the honest stage + class + code + a bounded,
//                            sanitized underlying diagnostic
//
// The `unknown` payload deliberately preserves a bounded single-line excerpt
// of the underlying error (MLX tensor/kernel diagnostics name shapes, dtypes
// and the failing stage, never prompt text) so the next device log identifies
// the failing stage instead of another anonymous "code 0".
//
// It is a pure function so it can be unit tested without a GPU, weights or a
// device. Stage attribution is supplied by the caller: the MLX-facing runtime
// sees the upstream error types (ModelFactoryError, tokenizer errors,
// MLXNN.UpdateError, MLXError) and maps them; this type stays MLX-free so the
// catalog module compiles and tests without the MLX toolchain.

import Foundation

/// The staged pipeline a local model load runs through. Reported inside the
/// `unknown` diagnostic so a host log can tell which stage failed without any
/// prompt text, path or credential ever leaving the device.
public enum LocalModelLoadStage: String, Sendable, Equatable, Codable {
    /// Deterministic snapshot audit that runs before any MLX work.
    case snapshotAudit
    /// config.json read/decode and model-type resolution.
    case configuration
    /// Tokenizer construction (tokenizer.json / chat template).
    case tokenizer
    /// Safetensors mapping, weight sanitize and parameter update.
    case weights
    /// Model container assembly and first graph evaluation on the GPU.
    case container
}

public enum LocalModelLoadFailure: Sendable, Equatable {
    public enum Kind: Sendable, Equatable {
        case corruptSnapshot(String)
        case insufficientMemory(required: UInt64, physical: UInt64)
        case unknown(String)
    }

    /// Lowercased fragments that identify an allocation failure in the
    /// bounded diagnostics MLX/CoreML surface. Kept deliberately specific:
    /// a false "memory" verdict would send the user to the wrong repair.
    static let memoryHints: [String] = [
        "out of memory",
        "outofmemory",
        "insufficient memory",
        "cannot allocate",
        "failed to allocate",
        "allocation failed",
        "resource limit",
        "exc_resource",
        "memory pressure",
        "kIOGPUCommandBufferCallbackErrorOutOfMemory".lowercased()
    ]

    /// Bound and sanitize an underlying error message for the user-visible
    /// diagnostic and the feedback log. MLX runtime text is generated by the
    /// framework from kernel names, dtypes and shapes — it never contains
    /// prompt text, credentials or tokens — but file-system failures can
    /// embed absolute sandbox paths (user names, UUID layouts). Sanitization
    /// is therefore real redaction, not just a length bound:
    ///
    /// - framework boilerplate prefixes are stripped;
    /// - absolute POSIX / drive-letter paths are replaced with `<path>`;
    /// - newlines are collapsed so the diagnostic stays one line;
    /// - the result is hard-bounded and whitespace-collapsed.
    public static func boundedMessage(_ error: Error, limit: Int = 160) -> String {
        var message = error.localizedDescription
        for prefix in ["MLX Error: ", "mlx::core::error: "] {
            if message.hasPrefix(prefix) {
                message = String(message.dropFirst(prefix.count))
            }
        }
        message = message
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\r", with: " ")
        message = redactPaths(in: message)
        var collapsed = ""
        collapsed.reserveCapacity(min(message.count, limit) + 1)
        var lastWasSpace = true
        for character in message {
            if character == " " {
                if lastWasSpace { continue }
                lastWasSpace = true
            } else {
                lastWasSpace = false
            }
            collapsed.append(character)
            if collapsed.count >= limit { break }
        }
        collapsed = collapsed.trimmingCharacters(in: .whitespaces)
        if collapsed.isEmpty { return "no diagnostic" }
        return collapsed.count > limit ? String(collapsed.prefix(limit)) : collapsed
    }

    /// Replaces absolute filesystem paths with a constant placeholder so the
    /// sandbox layout, device user name or app UUID can never leave the
    /// device inside a diagnostic. Relative fragments (kernel names such as
    /// `reduce.metal`) are preserved — they are the actionable part.
    static func redactPaths(in text: String) -> String {
        let pattern = #"(/(Users|home|var|private|tmp|Volumes|Applications|containers|Data)/[^\s]+)|([A-Za-z]:\\[^\s]+)"#
        guard let regex = try? NSRegularExpression(pattern: pattern) else { return text }
        let range = NSRange(text.startIndex..., in: text)
        return regex.stringByReplacingMatches(in: text, range: range, withTemplate: "<path>")
    }

    public static func classify(
        error: Error,
        snapshotProblems: [LocalModelSnapshotIntegrity.Problem] = [],
        mappedBytes: UInt64 = 0,
        headroomBytes: UInt64 = 0,
        stage: LocalModelLoadStage = .container
    ) -> Kind {
        if let problem = snapshotProblems.first {
            return .corruptSnapshot(problem.summary)
        }
        let nsError = error as NSError
        let description = ([nsError.localizedDescription] + (nsError.userInfo.values.compactMap { $0 as? String }))
            .joined(separator: " ")
            .lowercased()
        let looksLikeMemory = memoryHints.contains { description.contains($0) }
            || (mappedBytes > 0 && headroomBytes > 0 && mappedBytes > headroomBytes)
        if looksLikeMemory {
            return .insufficientMemory(required: mappedBytes, physical: headroomBytes)
        }
        // Preserve the failing stage plus a bounded, sanitized excerpt of the
        // underlying diagnostic. "code 0" alone identified nothing; the stage
        // and the first line of the real message are what make the next
        // device log actionable. No paths, no prompt text, hard budget.
        return .unknown(
            "stage=\(stage.rawValue) domain \(nsError.domain), code \(nsError.code), \(boundedMessage(error))"
        )
    }
}
