// FloeApp — Agent-facing remote image generation tool.

#if canImport(UIKit)
import Foundation
import CryptoKit
import FloeCore
import FloeModels
import FloeProviders
import FloeTools

struct RemoteImageGenerateTool: AgentTool {
    struct Arguments: Decodable, Sendable {
        var prompt: String
        var count: Int?
        var size: String?
    }

    static let name = "image.generate"
    static let toolDescription =
        "Generate images with the image model configured in Settings. Use this for user requests to draw, create, or render an image. Returns durable image artifacts; do not substitute SVG/HTML/Python when this tool is available."
    static let parametersJSON = #"""
    {
      "type": "object",
      "properties": {
        "prompt": {"type": "string", "description": "Detailed description of the image to create"},
        "count": {"type": "integer", "minimum": 1, "maximum": 4, "description": "Number of images; default 1"},
        "size": {"type": "string", "description": "Optional provider-supported size such as 1024x1024"}
      },
      "required": ["prompt"],
      "additionalProperties": false
    }
    """#
    static let riskLabels: Set<RiskLabel> = [.sendsDataToProvider, .writesFiles]
    static let isSideEffecting = true
    static let toolEffect: ToolEffect = .mutating

    private let generate: @MainActor @Sendable (String, Int, String?) async throws -> [AttachmentRef]
    private let resolveURL: @MainActor @Sendable (AttachmentRef) throws -> URL

    init(center: FilesCenter) {
        self.generate = { prompt, count, size in
            try await center.performRemoteImage(
                operation: .generate,
                prompt: prompt,
                count: count,
                size: size
            )
        }
        self.resolveURL = { attachment in
            try center.resolveURL(for: attachment)
        }
    }

    func validate(_ args: Arguments) throws {
        guard !args.prompt.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw FloeError.validationFailed("prompt must not be empty")
        }
        guard (1...4).contains(args.count ?? 1) else {
            throw FloeError.validationFailed("count must be 1...4")
        }
    }

    func execute(_ args: Arguments, context: ToolContext) async throws -> ToolExecutionOutput {
        try context.cancellation.throwIfCancelled()
        let attachments = try await generate(
            args.prompt.trimmingCharacters(in: .whitespacesAndNewlines),
            args.count ?? 1,
            args.size
        )
        let workspacePaths = try await persistInTaskWorkspace(
            attachments,
            context: context
        )
        let artifacts = attachments.compactMap { attachment -> ToolArtifactReference? in
            guard let relative = attachment.relativePath else { return nil }
            return ToolArtifactReference(
                id: attachment.id,
                relativePath: "GeneratedImages/\(relative)",
                mimeType: attachment.uti.contains("png") ? "image/png" : "image/jpeg",
                byteCount: attachment.byteCount,
                sha256: attachment.sha256
            )
        }
        let summary = zip(attachments, workspacePaths).map { attachment, path in
            "\(attachment.displayName) saved to \(path) [attachment:\(attachment.id.uuidString)]"
        }.joined(separator: "\n")
        let summaryDigest = SHA256.hash(data: Data(summary.utf8))
            .map { String(format: "%02x", $0) }.joined()
        return ToolExecutionOutput(
            summary: summary.isEmpty ? "No image was returned" : summary,
            fullOutputSHA256: summaryDigest,
            exitStatus: attachments.isEmpty ? 2 : 0,
            artifacts: artifacts
        )
    }

    /// Generated bytes remain in Floe's digest-verified artifact store for
    /// timeline rendering, and are also copied into the task workspace so
    /// the file inspector and later tools see the same durable result.
    private func persistInTaskWorkspace(
        _ attachments: [AttachmentRef],
        context: ToolContext
    ) async throws -> [String] {
        guard let root = context.workspaceRootURL else {
            throw FloeError.invalidConfiguration("No task workspace is available for generated images")
        }
        let canonicalRoot = root.standardizedFileURL.resolvingSymlinksInPath()
        var paths: [String] = []
        paths.reserveCapacity(attachments.count)
        for attachment in attachments {
            let ext = (attachment.displayName as NSString).pathExtension.lowercased()
            let filename = "generated-\(attachment.id.uuidString).\(ext.isEmpty ? "jpg" : ext)"
            let relativePath = "GeneratedImages/\(filename)"
            try context.authorizeWorkspacePath(relativePath)
            let destination = canonicalRoot.appendingPathComponent(relativePath)
            let resolvedParent = destination.deletingLastPathComponent()
                .resolvingSymlinksInPath()
            let rootPrefix = canonicalRoot.path.hasSuffix("/")
                ? canonicalRoot.path : canonicalRoot.path + "/"
            guard resolvedParent.path == canonicalRoot.path
                    || resolvedParent.path.hasPrefix(rootPrefix) else {
                throw FloeError.validationFailed("Generated image path escapes the task workspace")
            }
            try FileManager.default.createDirectory(
                at: destination.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
            let source = try await resolveURL(attachment)
            try FileManager.default.copyItem(at: source, to: destination)
            paths.append(relativePath)
        }
        return paths
    }
}

func registerRemoteImageTools(center: FilesCenter, registry: ToolRunnerRegistry = .shared) {
    ToolCatalog.register(RemoteImageGenerateTool.self)
    registry.register(RemoteImageGenerateTool(center: center))
}
#endif
