#!/usr/bin/env bash
# runner_upgrade_check.sh — focused existing-disk runner-upgrade check.
#
# This is a standalone check (it does NOT drive HostProtocolCheck or
# ChannelRouterCheck). It extracts the *production* declarations that own the
# upgrade path verbatim — LinuxGuestImage/…/LinuxGuestLimits and the
# qualification rules from FloeExecution/Linux/LinuxGuestService.swift, the
# disk-preparation + compatible-origin + runner-ledger code from
# LinuxGuestRuntimeImage.swift, the registry actor and its runner-upgrade flow
# from LinuxGuestRegistry.swift, the image verifier from
# LinuxGuestImageStore.swift and the whole command channel — and compiles them
# as one module under -swift-version 6 against a scripted guest console.
#
# What it proves with actual execution:
#   * an environment disk cloned from the manifest's declared predecessor is
#     adopted byte-for-byte (disk and origin.json untouched) and the legacy
#     runner inside it is upgraded in-guest from the verified standalone
#     runner artifact;
#   * an unrelated disk origin is still reported as a conflict and nothing is
#     overwritten;
#   * a missing/symlinked/wrong-size/wrong-digest runner artifact is rejected
#     before any in-guest replacement, with the disk preserved;
#   * the runner artifact obeys the shared structural/path/symlink/size/digest
#     checks (including a distinct `runner` role, never `disk`);
#   * the legacy probe is a live HELLO probe with a finite timeout, and the
#     ledger never substitutes for it;
#   * console reader ownership: production probe -> legacy serial channel ->
#     fresh production channel after the reboot, never two readers at once,
#     and the post-reboot CAPS is verified on the renewed stream;
#   * bounded admission: duplicate concurrent starts and a full guest
#     count/RAM budget are refused without killing a running guest, and the
#     reservation is released on failure and on stop.
#
# Usage: bash FloeAgent/LinuxGuest/tests/runner_upgrade_check.sh
# Env:
#   FLOE_GUEST_TEST_SCRATCH  scratch dir (default: mktemp under $TMPDIR)
#   FLOE_GUEST_KEEP_SCRATCH  1 = keep the scratch dir (artifacts stay)
#   FLOE_GUEST_SKIP_SWIFT6   1 = skip the -swift-version 6 typecheck
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
guest_root="$(cd "$here/.." && pwd)"
sources_root="$guest_root/../Sources"
linux_src="$sources_root/FloeExecution/Linux"
service_src="$linux_src/LinuxGuestService.swift"
runtime_image_src="$linux_src/LinuxGuestRuntimeImage.swift"
registry_src="$linux_src/LinuxGuestRegistry.swift"
channel_src="$linux_src/LinuxGuestCommandChannel.swift"
image_store_src="$linux_src/LinuxGuestImageStore.swift"
error_src="$sources_root/FloeCore/FloeError.swift"
token_src="$sources_root/FloeTools/ToolContext.swift"
result_src="$sources_root/FloeExecution/Packages/LinuxCommandService.swift"

for source in "$service_src" "$runtime_image_src" "$registry_src" "$channel_src" \
              "$image_store_src" "$error_src" "$token_src" "$result_src"; do
  if [ ! -f "$source" ]; then
    echo "missing source: $source" >&2
    exit 2
  fi
done

if [ -n "${FLOE_GUEST_TEST_SCRATCH:-}" ]; then
  scratch="$FLOE_GUEST_TEST_SCRATCH"
  mkdir -p "$scratch"
else
  scratch="$(mktemp -d "${TMPDIR:-/tmp}/floe-runner-upgrade-check.XXXXXX")"
  trap 'if [ "${FLOE_GUEST_KEEP_SCRATCH:-0}" != "1" ]; then rm -rf "$scratch"; fi' EXIT
fi

# The declarations below are extracted from the production sources by their
# column-0 declaration line and first column-0 closing brace (nested bodies are
# indented). Each block is checked after extraction so a moved declaration
# fails this script instead of silently compiling something else.
extract_module() {
  {
    echo "// Generated by runner_upgrade_check.sh — extracted production sources."
    echo "import Foundation"
    sed -n '/^public enum FloeError/,/^}$/p' "$error_src"
    sed -n '/^public final class CancellationToken/,/^}$/p' "$token_src"
    sed -n '/^public struct LinuxCommandResult/,/^}$/p' "$result_src"

    sed -n '/^public enum LinuxGuestError/,/^}$/p' "$service_src"
    sed -n '/^public struct LinuxGuestLimits/,/^}$/p' "$service_src"
    sed -n '/^public struct LinuxGuestShare/,/^}$/p' "$service_src"
    sed -n '/^public enum LinuxGuestMountPoint/,/^}$/p' "$service_src"
    sed -n '/^public struct LinuxGuestPathMap/,/^}$/p' "$service_src"
    sed -n '/^public struct LinuxGuestServiceForward/,/^}$/p' "$service_src"
    sed -n '/^public struct LinuxGuestEnvironmentDescriptor/,/^}$/p' "$service_src"
    sed -n '/^public protocol LinuxGuestEnvironmentProviding/,/^}$/p' "$service_src"
    sed -n '/^public struct LinuxGuestImageArtifact/,/^}$/p' "$service_src"
    sed -n '/^public struct LinuxGuestImageProvenance/,/^}$/p' "$service_src"
    sed -n '/^public struct LinuxGuestCompatibleDiskOrigin/,/^}$/p' "$service_src"
    sed -n '/^public struct LinuxGuestImage:/,/^}$/p' "$service_src"
    sed -n '/^public protocol LinuxGuestImageResolving/,/^}$/p' "$service_src"
    sed -n '/^public extension LinuxGuestImageResolving/,/^}$/p' "$service_src"
    sed -n '/^public struct LinuxGuestSessionInfo/,/^}$/p' "$service_src"
    sed -n '/^public struct LinuxGuestStatus/,/^}$/p' "$service_src"
    sed -n '/^public protocol LinuxGuestConsoleTransport/,/^}$/p' "$service_src"
    sed -n '/^enum LinuxGuestBootArguments/,/^}$/p' "$service_src"

    # Whole files: the runtime-image preparer has no FloeCore/FloeTools imports.
    cat "$runtime_image_src"

    # The registry actor plus its lifecycle seam (the command service and the
    # local-service extension are not part of this check).
    sed -n '/^public struct LinuxGuestSessionHandle/,/^}$/p' "$registry_src"
    sed -n '/^public protocol LinuxGuestSessionCreating/,/^}$/p' "$registry_src"
    sed -n '/^public actor TinyEMULinuxGuestRegistry/,/^}$/p' "$registry_src"

    # The whole production command channel, compiled as its own module.
    grep -v '^import FloeCore$' "$channel_src" | grep -v '^import FloeTools$'

    # The digest verifier (the import-only ZIPFoundation file is not needed).
    sed -n '/^public actor LinuxGuestImageVerifier/,/^}$/p' "$image_store_src"

    # Standalone seams for the two modules this check does not build
    # (FloeCore/FloeTools) and for the production session factory (its file
    # needs the vendored engine, which is not part of a host check). FloeDigest
    # is a real SHA-512, so digests here match production bytes.
    cat <<'STUBS'
import CryptoKit

enum FloeDigest {
    static func sha512Hex(_ data: Data) -> String {
        SHA512.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    static func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    static func sha512Hex(ofFileAt url: URL, chunkSize: Int = 1 << 20) throws -> String {
        let handle = try FileHandle(forReadingFrom: url)
        defer { try? handle.close() }
        var hasher = SHA512()
        while true {
            let chunk = try handle.read(upToCount: chunkSize) ?? Data()
            if chunk.isEmpty { break }
            hasher.update(data: chunk)
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }
}

struct FloeLogger {
    enum Category { case tools }
    init(category: Category) {}
    func info(_ message: @autoclosure () -> String) {}
    func error(_ message: @autoclosure () -> String) {}
}

struct HarnessTrustedImage {}

enum LinuxGuestImageDistributionCatalog {
    static func entry(id: String) -> HarnessTrustedImage? { nil }
}

/// The registry's public initializer has this as a default argument; the check
/// always injects its own factory.
public struct TinyEMUGuestSessionFactory: LinuxGuestSessionCreating {
    public init() {}

    public func makeSession(
        descriptor: LinuxGuestEnvironmentDescriptor,
        image: LinuxGuestImage,
        limits: LinuxGuestLimits
    ) throws -> LinuxGuestSessionHandle {
        throw LinuxGuestError.consoleUnavailable("the check injects its own session factory")
    }
}
STUBS
  } > "$scratch/GuestUpgradeModule.swift"

  local module="$scratch/GuestUpgradeModule.swift"
  check_declaration "$module" "public actor LinuxGuestCommandChannel"
  check_declaration "$module" "public actor TinyEMULinuxGuestRegistry"
  check_declaration "$module" "struct LinuxGuestRuntimeImagePreparer"
  check_declaration "$module" "public actor LinuxGuestImageVerifier"
  check_declaration "$module" "public struct LinuxGuestCompatibleDiskOrigin"
  check_declaration "$module" "case runner"
  check_declaration "$module" "func enterLegacySerialMode"
  check_declaration "$module" "func leaveLegacySerialMode"
  check_declaration "$module" "func resetRouterState"
  check_declaration "$module" "func loadVerifiedArtifact"
}

check_declaration() {
  if ! grep -q "$2" "$1"; then
    echo "extraction lost declaration '$2' (source moved?)" >&2
    exit 2
  fi
}

echo "==> extracting production upgrade module"
extract_module

if [ "${FLOE_GUEST_SKIP_SWIFT6:-0}" != "1" ]; then
  echo "==> strict typecheck (swift-version 6, object emit) of the extracted module"
  swiftc -swift-version 6 -c -o "$scratch/module.o" "$scratch/GuestUpgradeModule.swift"
fi

echo "==> compiling upgrade check (swift-version 6, object emit) and linking"
swiftc -swift-version 6 -o "$scratch/runner-upgrade-check" \
  "$here/RunnerUpgradeCheck.swift" "$scratch/GuestUpgradeModule.swift"

echo "==> running existing-disk upgrade checks"
"$scratch/runner-upgrade-check"

echo "==> all runner upgrade checks passed"
