// FloeApp — single in-app third-party license browser.
//
// SPDX-License-Identifier: MPL-2.0
//
// Settings exposes exactly one legal entry (Diagnostics & About → Legal →
// Third-Party Licenses). This file is that entry. It reads the packaged
// inventory that `scripts/license_inventory.sh` generates from the real
// dependency pins and upstream license files, and it reads every notice text
// from the file copied into this build:
//
//   Licenses/third-party-inventory.json   generated component + notice index
//   <bundlePath>                          complete notice text, verbatim
//
// There is deliberately no Swift-side copy of the dependency table: a version
// or license that is not in the generated manifest cannot appear on screen, and
// a notice missing from the build is shown as unavailable instead of hidden.
// The file name is retained from the previous TinyEMU-only view.

#if canImport(SwiftUI) && canImport(UIKit)
import SwiftUI
import UIKit

// MARK: - Generated manifest

/// The packaged license inventory generated by scripts/license_inventory.sh.
struct LicenseManifest: Decodable {
    struct Section: Decodable, Identifiable {
        let id: String
        let titleKey: String
        let fallback: String
    }

    struct Document: Decodable, Identifiable {
        let id: String
        /// Path relative to `FloeAgent/` in the repository.
        let repositoryPath: String
        /// Path inside the app bundle; the identity used by the reader.
        let bundlePath: String
        let titleKey: String
        let titleFallback: String
        let titleArgument: String?
        let license: String?
        let kindKey: String
        let required: Bool
        let section: String
        let noteKey: String?
    }

    struct Component: Decodable, Identifiable {
        let name: String
        let version: String
        let license: String
        let source: String
        let section: String
        let noteKey: String?

        var id: String { "\(name)@\(version)" }
    }

    struct Note: Decodable, Identifiable {
        let id: String
        let textKey: String
        let fallback: String
    }

    struct Counts: Decodable {
        let components: Int
        let documents: Int
        let pins: Int
    }

    let schemaVersion: Int
    let appLicense: String
    let repository: String
    let inventoryPath: String
    let sections: [Section]
    let documents: [Document]
    let components: [Component]
    let notes: [Note]
    let counts: Counts
}

/// Loads the generated manifest. `resourceRoot` is injectable so the lookup can
/// be exercised outside a running app bundle.
enum LicenseManifestLoader {
    static let bundlePath = "Licenses/third-party-inventory.json"

    static func load(resourceRoot: URL?, fileManager: FileManager = .default) -> LicenseManifest? {
        guard let root = resourceRoot else { return nil }
        let url = root.appendingPathComponent(bundlePath)
        guard fileManager.fileExists(atPath: url.path),
              let data = try? Data(contentsOf: url),
              let manifest = try? JSONDecoder().decode(LicenseManifest.self, from: data),
              manifest.schemaVersion >= 1
        else { return nil }
        return manifest
    }
}

/// Localizes a generated key, falling back to the manifest's canonical English
/// text when the catalog has no entry (an older build, or a newly generated
/// component that has not been translated yet).
enum LicenseLocalization {
    static func text(_ key: String, fallback: String) -> String {
        let value = String(localized: String.LocalizationValue(key))
        return value == key ? fallback : value
    }

    static func formatted(_ key: String, argument: String, fallback: String) -> String {
        String(format: text(key, fallback: fallback), argument)
    }
}

extension LicenseManifest {
    func sectionTitle(_ id: String) -> String {
        guard let section = sections.first(where: { $0.id == id }) else { return id }
        return LicenseLocalization.text(section.titleKey, fallback: section.fallback)
    }
}

// MARK: - Screen

struct ThirdPartyLicensesView: View {
    private let resourceRoot: URL?
    private let manifest: LicenseManifest?
    private let fileManager = FileManager.default

    init(resourceRoot: URL? = Bundle.main.resourceURL) {
        self.resourceRoot = resourceRoot
        self.manifest = LicenseManifestLoader.load(resourceRoot: resourceRoot)
    }

    var body: some View {
        Form {
            appSection
            if let manifest {
                bundledNoticesSection(manifest)
                componentInventorySection(manifest)
                notesSection(manifest)
            } else {
                Section {
                    Label("settings.licenses.manifest_missing", systemImage: "exclamationmark.triangle")
                        .foregroundStyle(FloeTheme.destructive)
                        .frame(minHeight: FloeTheme.minimumTarget)
                }
            }
            Section {
                Label("settings.diagnostics.privacy.note", systemImage: "hand.raised")
                    .font(FloeTheme.Typography.metadata)
                    .foregroundStyle(.secondary)
            }
        }
        .navigationTitle("settings.diagnostics.licenses")
        .navigationBarTitleDisplayMode(.inline)
        .accessibilityIdentifier("diagnostics.licenses")
    }

    // MARK: Sections

    private var appSection: some View {
        Section {
            LabeledContent("settings.licenses.this_app") {
                Text(verbatim: manifest?.appLicense ?? "MPL-2.0")
                    .foregroundStyle(.secondary)
            }
            .frame(minHeight: FloeTheme.minimumTarget)
            Link(destination: repositoryURL("LICENSE")) {
                Label("settings.licenses.repository_license", systemImage: "arrow.up.right.square")
            }
            .frame(minHeight: FloeTheme.minimumTarget)
        }
    }

    private func bundledNoticesSection(_ manifest: LicenseManifest) -> some View {
        Section {
            ForEach(orderedDocumentGroups(manifest), id: \.section.id) { group in
                Text(verbatim: manifest.sectionTitle(group.section.id))
                    .font(FloeTheme.Typography.metadata)
                    .foregroundStyle(.secondary)
                    .listRowInsets(EdgeInsets(top: 8, leading: 16, bottom: 2, trailing: 16))
                ForEach(group.documents) { document in
                    NavigationLink {
                        LicenseTextScreen(document: document, resourceRoot: resourceRoot)
                    } label: {
                        documentLabel(document, manifest: manifest)
                    }
                    .accessibilityIdentifier("diagnostics.license.\(document.bundlePath)")
                }
            }
        } header: {
            Text("settings.licenses.bundled.header")
        } footer: {
            Text("settings.licenses.bundled.footer")
        }
    }

    private func componentInventorySection(_ manifest: LicenseManifest) -> some View {
        Section {
            NavigationLink {
                LicenseComponentListScreen(manifest: manifest)
            } label: {
                VStack(alignment: .leading, spacing: 2) {
                    Text("settings.licenses.inventory.link")
                    Text(verbatim: String(
                        format: LicenseLocalization.text(
                            "settings.licenses.count",
                            fallback: "%d components"
                        ),
                        manifest.counts.components
                    ))
                    .font(FloeTheme.Typography.metadata)
                    .foregroundStyle(.secondary)
                }
                .frame(minHeight: FloeTheme.minimumTarget)
            }
            Link(destination: repositoryURL(manifest.inventoryPath)) {
                Label("settings.licenses.inventory.header", systemImage: "tablecells")
            }
            .frame(minHeight: FloeTheme.minimumTarget)
        } footer: {
            Text("settings.licenses.inventory.footer")
        }
    }

    @ViewBuilder
    private func notesSection(_ manifest: LicenseManifest) -> some View {
        if !manifest.notes.isEmpty {
            Section {
                ForEach(manifest.notes) { note in
                    Text(verbatim: LicenseLocalization.text(note.textKey, fallback: note.fallback))
                        .font(FloeTheme.Typography.metadata)
                        .foregroundStyle(.secondary)
                }
            } header: {
                Text("settings.licenses.notes.header")
            }
        }
    }

    // MARK: Rows

    private struct DocumentGroup {
        let section: LicenseManifest.Section
        let documents: [LicenseManifest.Document]
    }

    /// Keeps the generated section order; a section with no bundled notices is
    /// skipped instead of rendering an empty group.
    private func orderedDocumentGroups(_ manifest: LicenseManifest) -> [DocumentGroup] {
        manifest.sections.compactMap { section in
            let documents = manifest.documents.filter { $0.section == section.id }
            return documents.isEmpty ? nil : DocumentGroup(section: section, documents: documents)
        }
    }

    @ViewBuilder
    private func documentLabel(_ document: LicenseManifest.Document, manifest: LicenseManifest) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(verbatim: documentTitle(document))
            if let detail = documentDetail(document) {
                Text(verbatim: detail)
                    .font(FloeTheme.Typography.metadata)
                    .foregroundStyle(.secondary)
            }
            if let note = documentNote(document) {
                Text(verbatim: note)
                    .font(FloeTheme.Typography.metadata)
                    .foregroundStyle(.secondary)
            }
            if !isAvailable(document) {
                Text("settings.diagnostics.tinyemu_licenses.unavailable")
                    .font(FloeTheme.Typography.metadata)
                    .foregroundStyle(FloeTheme.destructive)
            }
        }
    }

    private func documentTitle(_ document: LicenseManifest.Document) -> String {
        let title = LicenseLocalization.text(document.titleKey, fallback: document.titleFallback)
        guard let argument = document.titleArgument else { return title }
        return String(format: title, argument)
    }

    private func documentDetail(_ document: LicenseManifest.Document) -> String? {
        let kind = LicenseLocalization.text(document.kindKey, fallback: document.kindKey)
        guard let license = document.license, !license.isEmpty else { return kind }
        return "\(license) · \(kind)"
    }

    /// Notice-specific note shipped in the catalog (for example the TinyEMU
    /// engine summary that the previous screen showed as its footer).
    private func documentNote(_ document: LicenseManifest.Document) -> String? {
        guard let key = document.noteKey else { return nil }
        let value = String(localized: String.LocalizationValue(key))
        return value == key ? nil : value
    }

    private func isAvailable(_ document: LicenseManifest.Document) -> Bool {
        guard let resourceRoot else { return false }
        return fileManager.fileExists(atPath: resourceRoot.appendingPathComponent(document.bundlePath).path)
    }

    private func repositoryURL(_ path: String) -> URL {
        let base = manifest?.repository ?? "https://github.com/JiangNanGenius/floe-agent"
        if let url = URL(string: "\(base)/blob/main/\(path)") { return url }
        return URL(string: base)!
    }
}

/// Full generated component inventory. The screen is its own list so a few
/// hundred components stay searchable and scroll without inflating the main
/// legal screen.
private struct LicenseComponentListScreen: View {
    let manifest: LicenseManifest

    @State private var query = ""

    var body: some View {
        List {
            ForEach(visibleSections, id: \.id) { section in
                Section {
                    ForEach(section.components) { component in
                        componentRow(component)
                    }
                } header: {
                    Text(verbatim: manifest.sectionTitle(section.id))
                }
            }
        }
        .searchable(text: $query, prompt: Text("settings.licenses.inventory.search"))
        .navigationTitle("settings.licenses.inventory.title")
        .navigationBarTitleDisplayMode(.inline)
        .accessibilityIdentifier("diagnostics.license.inventory")
    }

    private struct VisibleSection {
        let id: String
        let components: [LicenseManifest.Component]
    }

    private var visibleSections: [VisibleSection] {
        let needle = query.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        func matches(_ component: LicenseManifest.Component) -> Bool {
            guard !needle.isEmpty else { return true }
            return component.name.lowercased().contains(needle)
                || component.version.lowercased().contains(needle)
                || component.license.lowercased().contains(needle)
                || component.source.lowercased().contains(needle)
        }
        return manifest.sections.compactMap { section in
            let components = manifest.components
                .filter { $0.section == section.id && matches($0) }
                .sorted { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
            guard !components.isEmpty else { return nil }
            return VisibleSection(id: section.id, components: components)
        }
    }

    @ViewBuilder
    private func componentRow(_ component: LicenseManifest.Component) -> some View {
        if let url = URL(string: component.source), url.scheme?.hasPrefix("http") == true {
            Link(destination: url) {
                componentText(component)
            }
            .frame(minHeight: FloeTheme.minimumTarget)
        } else {
            componentText(component)
                .frame(minHeight: FloeTheme.minimumTarget)
        }
    }

    private func componentText(_ component: LicenseManifest.Component) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(verbatim: component.name)
            Text(verbatim: "\(component.version) · \(component.license)")
                .font(FloeTheme.Typography.metadata)
                .foregroundStyle(.secondary)
        }
    }
}

/// Reads and shows one bundled notice in full.
private struct LicenseTextScreen: View {
    let document: LicenseManifest.Document
    let resourceRoot: URL?

    @State private var text: String?
    @State private var loadFailure: String?

    var body: some View {
        Group {
            if let text {
                LicenseTextView(text: text)
                    .ignoresSafeArea(edges: .bottom)
            } else if let loadFailure {
                ScrollView {
                    Text(verbatim: loadFailure)
                        .font(FloeTheme.Typography.evidence)
                        .foregroundStyle(FloeTheme.destructive)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding()
                }
            } else {
                ProgressView()
            }
        }
        .navigationTitle(Text(verbatim: LicenseLocalization.text(document.titleKey, fallback: document.titleFallback)))
        .navigationBarTitleDisplayMode(.inline)
        .accessibilityIdentifier("diagnostics.license.text")
        .toolbar {
            ToolbarItem(placement: .primaryAction) {
                Button {
                    UIPasteboard.general.string = text
                } label: {
                    Label("action.copy", systemImage: "doc.on.doc")
                }
                .disabled(text?.isEmpty ?? true)
            }
        }
        .task(id: document.bundlePath) {
            guard text == nil, loadFailure == nil else { return }
            guard let resourceRoot else {
                loadFailure = String(localized: "settings.diagnostics.tinyemu_licenses.unavailable")
                return
            }
            let url = resourceRoot.appendingPathComponent(document.bundlePath)
            do {
                text = try String(contentsOf: url, encoding: .utf8)
            } catch {
                loadFailure = "\(String(localized: "settings.diagnostics.tinyemu_licenses.unavailable"))\n\(document.repositoryPath)"
            }
        }
    }
}

/// UIKit's text system virtualizes very large notices and always wraps them to
/// the available width; a two-axis SwiftUI ScrollView around one huge Text can
/// resolve to an unbounded size and render a blank page on iPad.
private struct LicenseTextView: UIViewRepresentable {
    let text: String

    func makeUIView(context: Context) -> UITextView {
        let view = UITextView()
        view.isEditable = false
        view.isSelectable = true
        view.alwaysBounceVertical = true
        view.alwaysBounceHorizontal = false
        view.textContainer.widthTracksTextView = true
        view.font = .monospacedSystemFont(ofSize: 12, weight: .regular)
        view.textColor = .label
        view.backgroundColor = .systemBackground
        view.textContainerInset = UIEdgeInsets(top: 16, left: 16, bottom: 16, right: 16)
        view.accessibilityIdentifier = "diagnostics.license.text.body"
        return view
    }

    func updateUIView(_ view: UITextView, context: Context) {
        guard view.text != text else { return }
        let offset = view.contentOffset
        view.text = text
        view.setContentOffset(offset, animated: false)
    }
}
#endif
