// FloeApp — single in-app third-party license browser.
//
// SPDX-License-Identifier: MPL-2.0
//
// Settings exposes exactly one legal entry (Diagnostics & About → Legal →
// Third-Party Licenses). This file is that entry: it keeps the complete
// TinyEMU/slirp notices and every other bundled dependency notice readable and
// copyable in place, and lists the components whose license text ships
// separately in the repository inventory.
//
// Nothing is summarised away. The full notices come from the files copied into
// the app bundle at build time; a notice that is missing from a build is
// reported as unavailable instead of being hidden. The component summary
// mirrors `FloeAgent/LICENSES-THIRD-PARTY.md` (generated by
// `scripts/license_inventory.sh`) for versions and sources, while the bundled
// texts remain the operative declarations.
//
// The file name is retained from the previous TinyEMU-only view: it is now the
// single unified license screen, so `DiagnosticsAboutView` has one entry.

#if canImport(SwiftUI) && canImport(UIKit)
import SwiftUI
import UIKit

// MARK: - Bundled notice discovery

/// One license or notice document copied into the app bundle.
struct BundledLicenseDocument: Identifiable, Hashable {
    /// Bundle-relative path; also the stable identity of the document.
    let relativePath: String
    let title: String
    let detail: String
    /// Required documents stay listed even when a build omitted the file, so
    /// the absence is visible instead of silently reducing the notices.
    let isRequired: Bool
    /// Optional grouping label for the list section.
    let section: String

    var id: String { relativePath }
}

/// Discovers the license texts that ship inside the app bundle.
///
/// Discovery is deliberately explicit: only paths that are actually declared as
/// resources are considered, and font families are enumerated from the bundled
/// folder. `resourceRoot` is injectable so the mapping can be tested without a
/// running app bundle.
enum BundledLicenseCatalog {
    /// The engine for which the previous settings screen existed separately.
    /// Kept first and always listed.
    static let tinyEMU = BundledLicenseDocument(
        relativePath: "TinyEMU-LICENSES.txt",
        title: "TinyEMU 2019-12-21 / slirp",
        detail: "MIT · BSD-2-Clause · BSD-3-Clause · Linux 客体条款 / Linux guest terms",
        isRequired: true,
        section: "引擎与运行器 / Engines and runners"
    )

    /// Every other notice copied into the bundle, in display order.
    static let known: [BundledLicenseDocument] = [
        .init(relativePath: "PDFiumLicenses/LICENSE", title: "PDFium", detail: "BSD-3-Clause · 完整文本 / full text", isRequired: false, section: "PDF 与归档 / PDF and archives"),
        .init(relativePath: "LibArchiveLicenses/COPYING", title: "libarchive", detail: "BSD-2-Clause · 完整文本 / full text", isRequired: false, section: "PDF 与归档 / PDF and archives"),
        .init(relativePath: "DocumentConversion/THIRD-PARTY-NOTICES.txt", title: "Office 文档转换 / Document conversion", detail: "html-to-docx · mammoth · turndown · marked 等 / and more", isRequired: false, section: "文档与工程 / Documents and engineering"),
        .init(relativePath: "DocumentConversion/FONT-LICENSE.txt", title: "文档转换字体 / Conversion fonts", detail: "随包字体授权 / bundled font grant", isRequired: false, section: "文档与工程 / Documents and engineering"),
        .init(relativePath: "EngineeringViewers/THIRD_PARTY_NOTICES.txt", title: "工程查看器 / Engineering viewers", detail: "pickr · gerber-to-svg 等 / and more", isRequired: false, section: "文档与工程 / Documents and engineering"),
        .init(relativePath: "EngineeringViewers/CAD_NOTICES.txt", title: "CAD 查看器 / CAD viewer", detail: "OCCT 相关声明 / OCCT-related notices", isRequired: false, section: "文档与工程 / Documents and engineering"),
        .init(relativePath: "EngineeringViewers/license.occt.txt", title: "Open CASCADE Technology", detail: "LGPL-2.1 · 完整文本 / full text", isRequired: false, section: "文档与工程 / Documents and engineering"),
        .init(relativePath: "EngineeringViewers/license.occt-import-js.txt", title: "occt-import-js", detail: "LGPL-2.1 · 完整文本 / full text", isRequired: false, section: "文档与工程 / Documents and engineering"),
        .init(relativePath: "EngineeringViewers/gerber-to-svg.min.js.LICENSE.txt", title: "gerber-to-svg (bundle notices)", detail: "随包依赖声明 / bundled dependency notices", isRequired: false, section: "文档与工程 / Documents and engineering"),
        .init(relativePath: "Whisper/NOTICE.txt", title: "Whisper 模型与分词器 / model and tokenizer", detail: "MIT · Apache-2.0 来源说明 / provenance", isRequired: false, section: "语音 / Speech"),
        .init(relativePath: "Whisper/WhisperKit-LICENSE.txt", title: "WhisperKit", detail: "MIT · 完整文本 / full text", isRequired: false, section: "语音 / Speech"),
        .init(relativePath: "Whisper/Tokenizer-LICENSE.txt", title: "Whisper tokenizer", detail: "Apache-2.0 · 完整文本 / full text", isRequired: false, section: "语音 / Speech"),
        .init(relativePath: "IDE/NOTICE.md", title: "CodeBlitz IDE / Offline IDE", detail: "MIT · CodeBlitz 2.4.6", isRequired: false, section: "IDE 与编辑器 / IDE and editor"),
        .init(relativePath: "IDE/vendor/LICENSE", title: "CodeBlitz bundled notices", detail: "打包依赖声明 / bundled dependency notices", isRequired: false, section: "IDE 与编辑器 / IDE and editor"),
        .init(relativePath: "IDE/vendor/MONACO-LICENSE", title: "OpenSumi Monaco", detail: "MIT · 完整文本 / full text", isRequired: false, section: "IDE 与编辑器 / IDE and editor"),
        .init(relativePath: "IDE/vendor/ONIGURUMA-LICENSE", title: "vscode-oniguruma", detail: "MIT 与 Oniguruma 声明 / and Oniguruma notices", isRequired: false, section: "IDE 与编辑器 / IDE and editor"),
        .init(relativePath: "IDE/vendor/CODICONS-LICENSE", title: "Microsoft Codicons", detail: "CC-BY-4.0 · 完整文本 / full text", isRequired: false, section: "IDE 与编辑器 / IDE and editor"),
        .init(relativePath: "IDE/vendor/codeblitz.global-with-react.min.js.LICENSE.txt", title: "CodeBlitz bundle notices", detail: "打包依赖声明 / bundled dependency notices", isRequired: false, section: "IDE 与编辑器 / IDE and editor"),
        .init(relativePath: "ZLImageEditor-LICENSE.txt", title: "ZLImageEditor", detail: "MIT · 完整文本 / full text", isRequired: false, section: "图像与媒体 / Image and media"),
        .init(relativePath: "LICENSE", title: "RoyalVNCKit", detail: "MIT · 完整文本 / full text", isRequired: false, section: "图像与媒体 / Image and media")
    ]

    static func documents(in resourceRoot: URL?, fileManager: FileManager = .default) -> [BundledLicenseDocument] {
        guard let root = resourceRoot else { return [tinyEMU] }
        var documents = [tinyEMU]
        documents += known.filter { fileManager.fileExists(atPath: root.appendingPathComponent($0.relativePath).path) }
        documents += fontDocuments(in: root, fileManager: fileManager)
        return documents
    }

    /// One entry per bundled font family that carries its own LICENSE.txt.
    private static func fontDocuments(in root: URL, fileManager: FileManager) -> [BundledLicenseDocument] {
        let fontsRoot = root.appendingPathComponent("Fonts/Bundled", isDirectory: true)
        guard let families = try? fileManager.contentsOfDirectory(
            at: fontsRoot,
            includingPropertiesForKeys: [.isDirectoryKey],
            options: [.skipsHiddenFiles]
        ) else { return [] }
        return families
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
            .compactMap { family in
                let license = family.appendingPathComponent("LICENSE.txt")
                guard fileManager.fileExists(atPath: license.path) else { return nil }
                let name = family.lastPathComponent
                return BundledLicenseDocument(
                    relativePath: "Fonts/Bundled/\(name)/LICENSE.txt",
                    title: "字体 / Font: \(name)",
                    detail: "OFL-1.1 或厂商授权 / OFL-1.1 or vendor grant",
                    isRequired: false,
                    section: "字体 / Fonts"
                )
            }
    }
}

// MARK: - Component summary

/// One runtime component whose versions and license identifiers are recorded
/// in the generated repository inventory. The bundled notice text (when one
/// ships) is the operative declaration; this row is the index entry.
struct LicenseComponent: Identifiable, Hashable {
    let name: String
    let version: String
    let license: String
    let source: String

    var id: String { "\(name)@\(version)" }

    init(_ name: String, _ version: String, _ license: String, _ source: String) {
        self.name = name
        self.version = version
        self.license = license
        self.source = source
    }
}

/// Component summary mirroring the non-font rows of
/// `FloeAgent/LICENSES-THIRD-PARTY.md` plus the engine rows declared by
/// `scripts/license_inventory.sh`. Regenerate this list when the inventory
/// changes; the full texts always come from the bundle.
enum LicenseInventory {
    struct Group: Identifiable {
        let id: String
        let title: String
        let components: [LicenseComponent]
    }

    static let groups: [Group] = [
        Group(id: "engines", title: "引擎与运行器 / Engines and runners", components: [
            .init("TinyEMU / FloeTinyEMU engine", "2019-12-21 + Floe patches", "MIT", "https://bellard.org/tinyemu/"),
            .init("TinyEMU slirp (compiled subset)", "2019-12-21", "BSD-2-Clause（Gasparovski）/ BSD-3-Clause（UC Regents）", "https://bellard.org/tinyemu/"),
            .init("Floe Linux guest component", "pinned catalog image", "Floe runner MPL-2.0；Debian 包许可证；kernel GPL-2.0；bbl BSD-3-Clause；static glibc LGPL-2.1", "https://github.com/JiangNanGenius/floe-agent/releases/tag/floe-linux-guest-20260920.1"),
            .init("VideoEditorKit", "c917b1e99ddc631b754a43704c05dfe3836e8183", "MIT", "https://github.com/didisouzacosta/VideoEditorKit"),
            .init("ZLImageEditor", "upstream + Floe integration", "MIT", "https://github.com/longitachi/ZLPhotoBrowser"),
            .init("FloeShellEngine (BSD shell core)", "upstream + Floe patch", "BSD-3-Clause", "https://github.com/holzschu/ios_system"),
            .init("FreeRDP bridge", "runtime.lock.json pin", "Apache-2.0", "https://github.com/FreeRDP/FreeRDP"),
            .init("ios_system command bus and BSD commands", "v3.0.4 manifest / v3.0.2 binaries", "BSD-3-Clause", "https://github.com/holzschu/ios_system"),
            .init("dash iOS", "0.5.11.5 + iOS port", "BSD-3-Clause", "https://github.com/holzschu/dash_iOS"),
            .init("ios_system libssh2", "1.11.0", "BSD-3-Clause", "https://github.com/holzschu/libssh2-apple"),
            .init("ios_system OpenSSL", "1.1.1w", "OpenSSL", "https://github.com/holzschu/openssl-apple"),
            .init("curl_ios", "v3.0.2 binary", "curl license (MIT/X derivative)", "https://github.com/holzschu/ios_system/tree/v3.0.4/curl_ios"),
            .init("WasmKit runtime", "0.2.2 + Floe budget patch", "MIT", "https://github.com/swiftwasm/WasmKit/tree/0.2.2"),
            .init("WasmKit SystemExtras", "0.2.2", "Apache-2.0 WITH Swift-exception", "https://github.com/swiftwasm/WasmKit/tree/0.2.2/Sources/SystemExtras"),
            .init("RoyalVNCKit (Floe synchronized queue)", "92d4427c73817d8f849bb289ff190aa4b40c44ea + Floe patch", "MIT", "https://github.com/JiangNanGenius/floe-agent/tree/main/FloeAgent/ThirdParty/RoyalVNCKit"),
            .init("llama.cpp", "b10581", "MIT", "https://github.com/ggml-org/llama.cpp"),
            .init("llama-ios-xcframework", "1.0.0", "MIT", "https://github.com/saitawngpha/llama-ios"),
            .init("PDFium", "chromium/8035", "BSD-3-Clause 及随包第三方声明", "https://pdfium.googlesource.com/pdfium/"),
            .init("pdfium-binaries", "chromium/8035", "MIT", "https://github.com/bblanchon/pdfium-binaries"),
            .init("libarchive", "3.8.9", "BSD-2-Clause 及 COPYING 例外", "https://github.com/libarchive/libarchive")
        ]),
        Group(id: "swift", title: "Swift 软件包 / Swift packages", components: [
            .init("mlx-swift", "ab924c82ead3b970caaa1c0ac11171de23f0305a", "MIT", "https://github.com/ml-explore/mlx-swift"),
            .init("mlx-swift-lm", "d5d8b290e601ac1bf11f24635f8f811a83b98bf8", "MIT", "https://github.com/ml-explore/mlx-swift-lm.git"),
            .init("whisperkit", "pinned commit 1e2a1637", "MIT", "https://github.com/argmaxinc/WhisperKit.git"),
            .init("grdb.swift", "7.8.0", "MIT", "https://github.com/groue/GRDB.swift.git"),
            .init("swift-nio", "2.88.0", "Apache-2.0", "https://github.com/apple/swift-nio.git"),
            .init("swift-nio-ssh", "0.3.6", "Apache-2.0", "https://github.com/Wellz26/swift-nio-ssh.git"),
            .init("swift-crypto", "3.15.1", "Apache-2.0", "https://github.com/apple/swift-crypto.git"),
            .init("swift-asn1", "1.7.1", "Apache-2.0", "https://github.com/apple/swift-asn1.git"),
            .init("swift-log", "1.15.0", "Apache-2.0", "https://github.com/apple/swift-log.git"),
            .init("swift-atomics", "1.3.1", "Apache-2.0", "https://github.com/apple/swift-atomics.git"),
            .init("swift-collections", "1.6.0", "Apache-2.0", "https://github.com/apple/swift-collections.git"),
            .init("swift-system", "1.8.0", "Apache-2.0", "https://github.com/apple/swift-system.git"),
            .init("swift-numerics", "1.1.1", "Apache-2.0", "https://github.com/apple/swift-numerics"),
            .init("swift-argument-parser", "1.8.2", "Apache-2.0", "https://github.com/apple/swift-argument-parser"),
            .init("swift-syntax", "603.0.2", "Apache-2.0", "https://github.com/swiftlang/swift-syntax.git"),
            .init("swift-huggingface", "0.9.0", "Apache-2.0", "https://github.com/huggingface/swift-huggingface.git"),
            .init("swift-transformers", "1.3.0", "Apache-2.0", "https://github.com/huggingface/swift-transformers.git"),
            .init("swift-jinja", "2.4.2", "Apache-2.0", "https://github.com/huggingface/swift-jinja.git"),
            .init("swift-jpeg", "2.1.0", "Apache-2.0", "https://github.com/tayloraswift/swift-jpeg"),
            .init("swift-png", "4.5.1", "Apache-2.0", "https://github.com/tayloraswift/swift-png"),
            .init("swiftterm", "1.10.0", "MIT", "https://github.com/migueldeicaza/SwiftTerm.git"),
            .init("swiftgitx", "0.4.0", "MIT", "https://github.com/ibrahimcetin/SwiftGitX.git"),
            .init("libgit2", "1.9.2", "UNKNOWN（仓库清单待复核 / pending review in the repository inventory）", "https://github.com/ibrahimcetin/libgit2.git"),
            .init("bigint", "5.7.0", "MIT", "https://github.com/attaswift/BigInt.git"),
            .init("bitbytedata", "2.1.0", "MIT", "https://github.com/tsolomko/BitByteData"),
            .init("swcompression", "4.9.1", "MIT", "https://github.com/tsolomko/SWCompression.git"),
            .init("zipfoundation", "0.9.20", "MIT", "https://github.com/weichsel/ZIPFoundation.git"),
            .init("citadel", "pinned manifest", "MIT", "https://github.com/orlandos-nl/Citadel.git"),
            .init("cryptoswift", "pinned manifest", "Zlib", "https://github.com/royalapplications/CryptoSwift.git"),
            .init("eventsource", "1.5.1", "MIT", "https://github.com/mattt/EventSource.git"),
            .init("smbclient", "0.2.1", "MIT", "https://github.com/kishikawakatsumi/SMBClient.git"),
            .init("yyjson", "0.12.0", "MIT", "https://github.com/ibireme/yyjson.git"),
            .init("h", "1.0.1", "Apache-2.0", "https://github.com/rarestype/h")
        ]),
        Group(id: "python", title: "Python 运行时与数据包 / Python runtimes and packages", components: [
            .init("CPython / Python-Apple-support", "3.13-b10", "PSF-2.0 及随包声明", "https://github.com/beeware/Python-Apple-support"),
            .init("NumPy iOS", "2.5.2.post1", "BSD-3-Clause", "https://anaconda.org/beeware/numpy"),
            .init("Pillow iOS", "11.0.0", "HPND 及随包声明", "https://anaconda.org/beeware/Pillow"),
            .init("pandas iOS", "3.0.5", "BSD-3-Clause 及随包声明", "https://github.com/JiangNanGenius/floe-agent/releases/tag/runtime-pandas-3.0.5-cp313"),
            .init("lxml iOS", "6.1.3", "BSD-3-Clause、PSF-2.0 及随包声明", "https://github.com/JiangNanGenius/floe-agent/releases/tag/runtime-lxml-6.1.3-cp313"),
            .init("libxml2 (lxml static dependency)", "2.14.6", "MIT 及随包声明", "https://gitlab.gnome.org/GNOME/libxml2"),
            .init("libxslt/libexslt (lxml static dependency)", "1.1.45", "MIT 及随包声明", "https://gitlab.gnome.org/GNOME/libxslt"),
            .init("python-docx", "1.2.0", "MIT", "https://pypi.org/project/python-docx/1.2.0/"),
            .init("python-pptx", "1.0.2", "MIT", "https://pypi.org/project/python-pptx/1.0.2/"),
            .init("regex iOS", "2026.9.10", "Apache-2.0", "https://github.com/JiangNanGenius/floe-agent/releases/tag/runtime-regex-2026.9.10-cp313"),
            .init("PyYAML iOS", "6.0.3", "MIT", "https://github.com/JiangNanGenius/floe-agent/releases/tag/runtime-pyyaml-6.0.3-cp313"),
            .init("MarkupSafe iOS", "3.0.3", "BSD-3-Clause", "https://github.com/JiangNanGenius/floe-agent/releases/tag/runtime-markupsafe-3.0.3-cp313"),
            .init("zstandard iOS", "0.25.0", "BSD-3-Clause", "https://github.com/JiangNanGenius/floe-agent/releases/tag/runtime-zstandard-0.25.0-cp313"),
            .init("Brotli iOS", "1.2.0", "MIT", "https://github.com/JiangNanGenius/floe-agent/releases/tag/runtime-brotli-1.2.0-cp313"),
            .init("greenlet iOS", "3.5.5", "MIT AND PSF-2.0", "https://github.com/JiangNanGenius/floe-agent/releases/tag/runtime-greenlet-3.5.5-cp313"),
            .init("frozenlist iOS", "1.8.0", "Apache-2.0", "https://github.com/JiangNanGenius/floe-agent/releases/tag/runtime-frozenlist-1.8.0-cp313"),
            .init("multidict iOS", "6.8.0", "Apache-2.0", "https://github.com/JiangNanGenius/floe-agent/releases/tag/runtime-multidict-6.8.0-cp313"),
            .init("python-dateutil", "2.9.0.post0", "Apache-2.0 OR BSD-3-Clause", "https://pypi.org/project/python-dateutil/2.9.0.post0/"),
            .init("six", "1.17.0", "MIT", "https://pypi.org/project/six/1.17.0/"),
            .init("tzdata", "2026.3", "Apache-2.0", "https://pypi.org/project/tzdata/2026.3/")
        ]),
        Group(id: "web", title: "文档转换、IDE 与字体 / Conversion, IDE and fonts", components: [
            .init("@turbodocx/html-to-docx", "1.22.2", "MIT", "https://www.npmjs.com/package/@turbodocx/html-to-docx"),
            .init("mammoth", "1.12.2", "BSD-2-Clause", "https://www.npmjs.com/package/mammoth"),
            .init("turndown / turndown-plugin-gfm", "7.2.4 / 1.0.2", "MIT", "https://www.npmjs.com/package/turndown"),
            .init("marked", "18.0.12", "MIT", "https://www.npmjs.com/package/marked"),
            .init("jszip", "3.10.1", "MIT", "https://www.npmjs.com/package/jszip"),
            .init("dompurify", "3.4.15", "(MPL-2.0 OR Apache-2.0)", "https://www.npmjs.com/package/dompurify"),
            .init("html-minifier-terser", "7.2.0", "MIT", "https://www.npmjs.com/package/html-minifier-terser"),
            .init("OpenSumi CodeBlitz", "2.4.6", "MIT", "https://github.com/opensumi/codeblitz"),
            .init("OpenSumi Monaco", "3.6.5-next-1766394426.0", "MIT", "https://github.com/opensumi/monaco-editor"),
            .init("vscode-oniguruma", "1.5.1", "MIT 及 Oniguruma 声明", "https://github.com/microsoft/vscode-oniguruma"),
            .init("Microsoft Codicons", "0.0.35", "CC-BY-4.0", "https://github.com/microsoft/vscode-codicons"),
            .init("Open CASCADE Technology (OCCT)", "pinned by EngineeringViewers", "LGPL-2.1（随包完整文本）", "https://github.com/Open-Cascade-SAS/OCCT"),
            .init("occt-import-js", "pinned by EngineeringViewers", "LGPL-2.1（随包完整文本）", "https://github.com/kovacsv/occt-import-js"),
            .init("@simonwep/pickr", "1.9.0", "MIT", "https://github.com/simonwep/pickr"),
            .init("FloeDocumentSans (modified Noto Sans SC)", "2.004", "OFL-1.1", "https://github.com/notofonts/noto-cjk/tree/523d033d6cb47f4a80c58a35753646f5c3608a78"),
            .init("内置中文字体 / Bundled CJK fonts", "27 families", "OFL-1.1 或厂商授权（逐字体完整文本随包）", "see the bundled Fonts/Bundled notice texts")
        ])
    ]
}

// MARK: - Screen

struct ThirdPartyLicensesView: View {
    private let resourceRoot: URL?
    private let documents: [BundledLicenseDocument]
    private let fileManager = FileManager.default

    init(resourceRoot: URL? = Bundle.main.resourceURL) {
        self.resourceRoot = resourceRoot
        self.documents = BundledLicenseCatalog.documents(in: resourceRoot)
    }

    var body: some View {
        Form {
            Section {
                LabeledContent("应用自身 / This app") {
                    Text("MPL-2.0").foregroundStyle(.secondary)
                }
                .frame(minHeight: FloeTheme.minimumTarget)
                Link(destination: Self.repositoryURL("LICENSE")) {
                    Label("仓库 LICENSE / Repository LICENSE", systemImage: "arrow.up.right.square")
                }
                .frame(minHeight: FloeTheme.minimumTarget)
            } header: {
                Text("许可 / License")
            }

            Section {
                ForEach(documents) { document in
                    NavigationLink {
                        LicenseTextScreen(document: document, resourceRoot: resourceRoot)
                    } label: {
                        documentLabel(document)
                    }
                    .accessibilityIdentifier("diagnostics.license.\(document.relativePath)")
                }
            } header: {
                Text("随包许可全文 / Bundled license notices")
            } footer: {
                Text("settings.diagnostics.tinyemu_licenses.footer")
            }

            ForEach(LicenseInventory.groups) { group in
                Section {
                    ForEach(group.components) { component in
                        componentRow(component)
                    }
                } header: {
                    Text(verbatim: group.title)
                }
            }

            Section {
                Link(destination: Self.repositoryURL("LICENSES-THIRD-PARTY.md")) {
                    Label("仓库构件清单 / Repository component inventory", systemImage: "tablecells")
                }
                .frame(minHeight: FloeTheme.minimumTarget)
            } footer: {
                Text(verbatim: "版本与源码地址以仓库 LICENSES-THIRD-PARTY.md（由 scripts/license_inventory.sh 生成）为准；本页全文来自 App 包内文件。缺失的随包文件会明确显示为不可用，不会被静默省略。 / Versions and sources follow FloeAgent/LICENSES-THIRD-PARTY.md in the repository; every full text on this screen comes from the app bundle, and a missing bundled file is reported instead of hidden.")
            }

            Section {
                Label("settings.diagnostics.privacy.note", systemImage: "hand.raised")
                    .font(FloeTheme.Typography.metadata)
                    .foregroundStyle(.secondary)
            }
        }
        .navigationTitle("settings.diagnostics.licenses")
        .navigationBarTitleDisplayMode(.inline)
        .accessibilityIdentifier("diagnostics.licenses")
    }

    @ViewBuilder
    private func documentLabel(_ document: BundledLicenseDocument) -> some View {
        let available = resourceRoot.map {
            fileManager.fileExists(atPath: $0.appendingPathComponent(document.relativePath).path)
        } ?? false
        VStack(alignment: .leading, spacing: 2) {
            Text(verbatim: document.title)
            Text(verbatim: document.detail)
                .font(FloeTheme.Typography.metadata)
                .foregroundStyle(.secondary)
            if !available {
                Text("settings.diagnostics.tinyemu_licenses.unavailable")
                    .font(FloeTheme.Typography.metadata)
                    .foregroundStyle(FloeTheme.destructive)
            }
        }
    }

    @ViewBuilder
    private func componentRow(_ component: LicenseComponent) -> some View {
        if let url = URL(string: component.source), url.scheme?.hasPrefix("http") == true {
            Link(destination: url) {
                componentText(component)
            }
            .frame(minHeight: FloeTheme.minimumTarget)
        } else {
            componentText(component)
                .frame(minHeight: FloeTheme.minimumTarget)
        }
    }

    private func componentText(_ component: LicenseComponent) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(verbatim: component.name)
            Text(verbatim: "\(component.version) · \(component.license)")
                .font(FloeTheme.Typography.metadata)
                .foregroundStyle(.secondary)
        }
    }

    private static func repositoryURL(_ path: String) -> URL {
        URL(string: "https://github.com/JiangNanGenius/floe-agent/blob/main/FloeAgent/\(path)")!
    }
}

/// Reads and shows one bundled notice in full.
private struct LicenseTextScreen: View {
    let document: BundledLicenseDocument
    let resourceRoot: URL?

    @State private var text: String?
    @State private var loadFailure: String?

    var body: some View {
        Group {
            if let text {
                LicenseTextView(text: text)
                    .ignoresSafeArea(edges: .bottom)
            } else if let loadFailure {
                ScrollView {
                    Text(verbatim: loadFailure)
                        .font(FloeTheme.Typography.evidence)
                        .foregroundStyle(FloeTheme.destructive)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding()
                }
            } else {
                ProgressView()
            }
        }
        .navigationTitle(Text(verbatim: document.title))
        .navigationBarTitleDisplayMode(.inline)
        .accessibilityIdentifier("diagnostics.license.text")
        .toolbar {
            ToolbarItem(placement: .primaryAction) {
                Button {
                    UIPasteboard.general.string = text
                } label: {
                    Label("action.copy", systemImage: "doc.on.doc")
                }
                .disabled(text?.isEmpty ?? true)
            }
        }
        .task(id: document.relativePath) {
            guard text == nil, loadFailure == nil else { return }
            guard let resourceRoot else {
                loadFailure = String(localized: "settings.diagnostics.tinyemu_licenses.unavailable")
                return
            }
            let url = resourceRoot.appendingPathComponent(document.relativePath)
            do {
                text = try String(contentsOf: url, encoding: .utf8)
            } catch {
                loadFailure = "\(String(localized: "settings.diagnostics.tinyemu_licenses.unavailable"))\n\(document.relativePath)"
            }
        }
    }
}

/// UIKit's text system virtualizes very large notices and always wraps them to
/// the available width; a two-axis SwiftUI ScrollView around one huge Text can
/// resolve to an unbounded size and render a blank page on iPad.
private struct LicenseTextView: UIViewRepresentable {
    let text: String

    func makeUIView(context: Context) -> UITextView {
        let view = UITextView()
        view.isEditable = false
        view.isSelectable = true
        view.alwaysBounceVertical = true
        view.alwaysBounceHorizontal = false
        view.textContainer.widthTracksTextView = true
        view.font = .monospacedSystemFont(ofSize: 12, weight: .regular)
        view.textColor = .label
        view.backgroundColor = .systemBackground
        view.textContainerInset = UIEdgeInsets(top: 16, left: 16, bottom: 16, right: 16)
        view.accessibilityIdentifier = "diagnostics.license.text.body"
        return view
    }

    func updateUIView(_ view: UITextView, context: Context) {
        guard view.text != text else { return }
        let offset = view.contentOffset
        view.text = text
        view.setContentOffset(offset, animated: false)
    }
}
#endif
