#!/usr/bin/env python3
"""Reproduce small upstream decoder fixtures from the pinned libarchive source."""
import base64
import binascii
import hashlib
from pathlib import Path
import sys
import tarfile

archive = Path(sys.argv[1])
assert hashlib.sha256(archive.read_bytes()).hexdigest() == "f5a6539059cf5e597dbeda37bfa4874b1e8dea063c8d93bf85a2b44af90a5bd4"
names = ["test_read_format_rar.rar", "test_read_format_rar_windows.rar", "test_read_format_rar4_encrypted_filenames.rar",
         "test_read_format_rar5_compressed.rar", "test_read_format_rar5_encrypted.rar",
         "test_read_format_rar5_multiarchive.part01.rar"]
lines = ["// Generated by scripts/generate_rar_test_fixtures.py from libarchive 3.8.9.",
         "// BSD-2-Clause; see Resources/LibArchiveLicenses/COPYING and upstream tests.",
         "enum RARFixtures {", "    static let encoded: [String: String] = ["]
with tarfile.open(archive) as tar:
    notices = []
    for source_name in ["test_read_format_rar.c", "test_read_format_rar5.c"]:
        source_text = tar.extractfile("libarchive-3.8.9/libarchive/test/" + source_name).read().decode()
        notices.append(source_name + "\n" + source_text[:source_text.index("*/") + 2])
    for name in names:
        source = tar.extractfile("libarchive-3.8.9/libarchive/test/" + name + ".uu").read().splitlines()
        start = next(i for i, line in enumerate(source) if line.startswith(b"begin ")) + 1
        payload = bytearray()
        for line in source[start:]:
            if line == b"end":
                break
            payload.extend(binascii.a2b_uu(line))
        lines.append(f'        "{name}": "{base64.b64encode(payload).decode()}",')
lines.extend(["    ]", "}", ""])
destination = Path(__file__).resolve().parent.parent / "Tests/FloeAgentUITests/RARFixtures.generated.swift"
destination.write_text("\n".join(lines))
(destination.parent / "RARFixtures.LICENSE.txt").write_text("\n\n".join(notices) + "\n")
