#!/bin/bash
# license_inventory.sh — Parse Package.resolved and the ThirdParty manifest
# into LICENSES-THIRD-PARTY.md. Allowlist: MPL-2.0 / MIT / BSD / Apache-2.0;
# GPL-family licenses fail the build.
set -euo pipefail

cd "$(dirname "$0")/.."

OUTPUT="LICENSES-THIRD-PARTY.md"

python3 - <<'PY'
import json, subprocess, sys

ALLOWED = {"MIT", "BSD-2-Clause", "BSD-3-Clause", "Apache-2.0", "MPL-2.0", "ISC", "0BSD"}
GPL_FAMILY = {"GPL-2.0", "GPL-3.0", "LGPL-2.1", "LGPL-3.0", "AGPL-3.0"}

with open("Package.resolved") as f:
    pins = json.load(f)["pins"]

rows = []
violations = []
for pin in sorted(pins, key=lambda p: p["identity"]):
    identity = pin["identity"]
    location = pin["location"]
    version = pin["state"].get("version", "unknown")
    # Detect license from the checked-out dependency when available.
    checkout = f".build/checkouts/{identity}"
    license_name = "UNKNOWN"
    try:
        for candidate in ("LICENSE", "LICENSE.md", "LICENSE.txt", "LICENCE"):
            try:
                with open(f"{checkout}/{candidate}") as lf:
                    head = lf.read(2048).lower()
                if "apache license" in head:
                    license_name = "Apache-2.0"
                elif "mozilla public license" in head:
                    license_name = "MPL-2.0"
                elif "mit license" in head or "permission is hereby granted, free of charge" in head:
                    license_name = "MIT"
                elif "redistribution and use in source and binary forms" in head:
                    license_name = "BSD-3-Clause"
                elif "gnu general public license" in head:
                    license_name = "GPL-3.0"
                break
            except FileNotFoundError:
                continue
    except Exception:
        pass
    rows.append((identity, version, license_name, location))
    if license_name in GPL_FAMILY:
        violations.append(f"{identity}: GPL-family license {license_name}")
    elif license_name == "UNKNOWN":
        print(f"warning: {identity}: license undetected, manual review required", file=sys.stderr)

with open("LICENSES-THIRD-PARTY.md", "w") as out:
    out.write("# Third-Party Licenses\n\n")
    out.write("Generated by scripts/license_inventory.sh. Do not edit by hand.\n\n")
    out.write("| Package | Version | License | Source |\n|---|---|---|---|\n")
    for identity, version, license_name, location in rows:
        out.write(f"| {identity} | {version} | {license_name} | {location} |\n")

if violations:
    print("error: GPL-family licenses are not allowed:", file=sys.stderr)
    for v in violations:
        print(f"  - {v}", file=sys.stderr)
    sys.exit(1)

print(f"license_inventory OK: {len(rows)} dependencies inventoried")
PY
