;; Streaming ASCII uppercase filter. UTF-8 non-ASCII bytes remain unchanged.
(module
  (import "wasi_snapshot_preview1" "fd_read" (func $read (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $write (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "proc_exit" (func $exit (param i32)))
  (memory (export "memory") 1 1)
  (func (export "_start") (local $n i32) (local $i i32) (local $c i32)
    (loop $readloop
      (i32.store (i32.const 0) (i32.const 32))
      (i32.store (i32.const 4) (i32.const 4096))
      (if (call $read (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 8))
        (then (call $exit (i32.const 1))))
      (local.set $n (i32.load (i32.const 8)))
      (if (i32.eqz (local.get $n)) (then (return)))
      (local.set $i (i32.const 0))
      (loop $chars
        (local.set $c (i32.load8_u (i32.add (i32.const 32) (local.get $i))))
        (if (i32.and (i32.ge_u (local.get $c) (i32.const 97)) (i32.le_u (local.get $c) (i32.const 122)))
          (then (i32.store8 (i32.add (i32.const 32) (local.get $i)) (i32.sub (local.get $c) (i32.const 32)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br_if $chars (i32.lt_u (local.get $i) (local.get $n))))
      (i32.store (i32.const 4) (local.get $n))
      (loop $writeall
        (if (call $write (i32.const 1) (i32.const 0) (i32.const 1) (i32.const 12))
          (then (call $exit (i32.const 1))))
        (local.set $i (i32.load (i32.const 12)))
        (if (i32.eqz (local.get $i)) (then (call $exit (i32.const 1))))
        (local.set $n (i32.sub (local.get $n) (local.get $i)))
        (i32.store (i32.const 0) (i32.add (i32.load (i32.const 0)) (local.get $i)))
        (i32.store (i32.const 4) (local.get $n))
        (br_if $writeall (local.get $n)))
      (br $readloop))))
