#!/usr/bin/env python3
"""Generate the Swift qualification scenario inside the restored app tree.

The upstream MobileUITests target uses a PBXFileSystemSynchronizedRootGroup
(verified at the pinned commit: no membership exceptions for MobileUITests), so
dropping one file into ios/MobileUITests/Tests/ adds it to the genuine test
target without touching the Xcode project.

The scenario drives REAL controls and verifies REAL state.  Native sequence:

  1. open the seeded PPTX (iPad starts in view mode)              preview-open
  2. close it again immediately                                   preview-close
     -- rapid preview close/reopen is mandatory: the reported device failure
        is on the second native open, which a single open+edit session
        bypasses entirely
  3. reopen the same file                                         reopen-before-edit
  4. tap the floating "Edit document" control and require the
     Impress edit controls to appear                              enter-edit
  5. tap "Insert Slide" and require the slide count to move to 3  insert-slide
  6. stay in edit for 120 s and require the editor is still alive idle-120s
  7. tap the real Save control                                    save
  8. leave edit through a real control ("Read mode", else the
     Editing -> Viewing Mode dropdown) and require the floating
     "Edit document" control to reappear (read-only state)        leave-edit
  9. close from view mode with the upstream Lifecycle close
     control and require the document browser to return           close
 10. reopen the file and require the editor to load again         reopen
 11. close again                                                  close-after-reopen

The receipt is attached as the typed XCTAttachment "sim-qual-receipt" in a
``defer``, so a failure receipt is retained too; it is never swallowed and
structural errors are reported inside the receipt.  A best-effort copy also
goes to the UITest *runner* container for diagnostics only -- the persistence
gate reads the xcresult attachment, not the host app container.

This is host-only (upstream Mobile), never the Floe app.
"""
import argparse
import json
from pathlib import Path

from sim_paths import (FIXTURE_BASENAME, IDLE_SECONDS, EDITOR_LOAD_TIMEOUT,
                       RECEIPT_ATTACHMENT_NAME, SCENARIO_NATIVE_SEQUENCE,
                       SCENARIO_PHASES)

SWIFT_TEMPLATE = r'''// -*- Mode: swift; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4; fill-column: 100 -*-
// GENERATED by scripts/office_real_simulator/qualification_ui_test.py
// Do not edit by hand; the generator runs in the cloud workspace.
//
// Real-engine simulator qualification, host-only (upstream Mobile app).
// Native sequence actually driven:
//   @@NATIVE_SEQUENCE@@
// Rapid preview close/reopen runs BEFORE edit because the reported device
// failure path is the second native open; a single open+edit session never
// reaches it.
//
// A UI test executes in its own runner process: FileManager documents here are
// the RUNNER container. The authoritative receipt is the typed
// "sim-qual-receipt" XCTAttachment (retained even on failure); the runner
// Documents copy is diagnostics only. The persistence gate reads the
// attachment, never the host app container for this file.

import XCTest

final class FloeRealSimulatorQualification: XCTestCase {
    static let fixtureBasename = "@@FIXTURE_BASENAME@@"
    static let fixtureStem = "@@FIXTURE_STEM@@"
    static let idleSeconds: TimeInterval = @@IDLE_SECONDS@@
    static let loadTimeout: TimeInterval = @@LOAD_TIMEOUT@@
    static let receiptAttachmentName = "@@RECEIPT_NAME@@"
    static let expectedPhases = [@@PHASES@@]
    static let nativeSequence = "@@NATIVE_SEQUENCE@@"
    static var receipt: [String: Any] = [:]

    override func setUpWithError() throws {
        continueAfterFailure = false
        XCUIDevice.shared.orientation = UIDeviceOrientation.landscapeLeft
    }

    func mark(_ phase: String, _ ok: Bool, _ detail: String = "") {
        var phases = FloeRealSimulatorQualification.receipt["phases"] as? [[String: Any]] ?? []
        phases.append(["phase": phase, "ok": ok, "detail": detail,
                       "elapsed": Date().timeIntervalSince1970])
        FloeRealSimulatorQualification.receipt["phases"] = phases
        FloeRealSimulatorQualification.receipt["fixture"] =
            FloeRealSimulatorQualification.fixtureBasename
    }

    func shot(_ name: String) {
        let attachment = XCTAttachment(screenshot: XCUIScreen.main.screenshot())
        attachment.name = name
        attachment.lifetime = .keepAlways
        add(attachment)
    }

    /// Always attach the receipt, success or failure. This is the receipt the
    /// persistence gate extracts from the xcresult; it is never swallowed.
    func attachReceipt() {
        FloeRealSimulatorQualification.receipt["expectedPhases"] =
            FloeRealSimulatorQualification.expectedPhases
        FloeRealSimulatorQualification.receipt["nativeSequence"] =
            FloeRealSimulatorQualification.nativeSequence
        FloeRealSimulatorQualification.receipt["hostKind"] = "upstream-mobile-host-only"
        var data: Data
        do {
            data = try JSONSerialization.data(
                withJSONObject: FloeRealSimulatorQualification.receipt,
                options: [.prettyPrinted, .sortedKeys])
        } catch {
            FloeRealSimulatorQualification.receipt["serializationError"] = "\(error)"
            data = Data("{\"serializationError\": \"\(error)\"}".utf8)
        }
        let attachment = XCTAttachment(data: data, uniformTypeIdentifier: "public.json")
        attachment.name = FloeRealSimulatorQualification.receiptAttachmentName
        attachment.lifetime = .keepAlways
        add(attachment)
        // Diagnostics-only copy in the UITest runner container (not the gate source).
        if let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first {
            let url = docs.appendingPathComponent(
                FloeRealSimulatorQualification.receiptAttachmentName + ".json")
            do {
                try data.write(to: url, options: .atomic)
            } catch {
                NSLog("FloeQualification: runner receipt copy not written: \(error)")
            }
        }
    }

    func require(_ condition: Bool, _ phase: String, _ message: String) throws {
        guard condition else {
            mark(phase, false, message)
            throw NSError(domain: "FloeRealSimulatorQualification", code: 1,
                          userInfo: [NSLocalizedDescriptionKey: message])
        }
    }

    @MainActor
    func firstElement(_ app: XCUIApplication, _ labels: [String],
                      includeMenuItems: Bool = false) -> XCUIElement? {
        for label in labels {
            let direct = app.buttons[label]
            if direct.exists { return direct }
            let identified = app.buttons.matching(identifier: label).firstMatch
            if identified.exists { return identified }
            let byLabel = app.buttons.matching(
                NSPredicate(format: "label == %@", label)).firstMatch
            if byLabel.exists { return byLabel }
            let text = app.staticTexts.matching(
                NSPredicate(format: "label == %@", label)).firstMatch
            if text.exists { return text }
            if includeMenuItems {
                let menu = app.menuItems[label]
                if menu.exists { return menu }
                let menuByLabel = app.menuItems.matching(
                    NSPredicate(format: "label == %@", label)).firstMatch
                if menuByLabel.exists { return menuByLabel }
            }
        }
        return nil
    }

    @MainActor
    func firstElementWaiting(_ app: XCUIApplication, _ labels: [String],
                             timeout: TimeInterval) -> XCUIElement? {
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            if let element = firstElement(app, labels, includeMenuItems: true) {
                return element
            }
            Thread.sleep(forTimeInterval: 0.5)
        }
        return nil
    }

    /// Real slide-count verification: the Impress status/preview exposes
    /// "of <n>", "preview of page <n>" and "Slide <n>" in the accessibility tree.
    @MainActor
    func waitForSlideCount(_ app: XCUIApplication, expected: Int,
                           timeout: TimeInterval) -> Bool {
        let deadline = Date().addingTimeInterval(timeout)
        let ofCount = "of \(expected)"
        let page = "preview of page \(expected)"
        let slide = "Slide \(expected)"
        while Date() < deadline {
            if app.staticTexts.matching(
                NSPredicate(format: "label CONTAINS %@", ofCount)).firstMatch.exists {
                return true
            }
            let predicate = NSPredicate(format: "label CONTAINS %@ OR label CONTAINS %@",
                                        page, slide)
            if app.descendants(matching: .any).matching(predicate).firstMatch.exists {
                return true
            }
            Thread.sleep(forTimeInterval: 0.5)
        }
        return false
    }

    @MainActor
    func openFixture(_ app: XCUIApplication, phase: String) throws -> XCUIElement {
        try DocumentBrowser.ensureSidebarShown(app: app)
        let onDevice = app.cells["DOC.sidebar.item.On My iPad"]
        try require(onDevice.waitForExistence(timeout: 20), phase, "On My iPad missing")
        onDevice.tap()
        let mainAppName = app.label
        let container = app.cells["\(mainAppName), Container"]
        try require(container.waitForExistence(timeout: 10), phase,
                    "App container cell missing")
        container.tap()
        let folder = app.cells["TestFiles, Folder"]
        try require(folder.waitForExistence(timeout: 10), phase, "TestFiles folder missing")
        folder.tap()
        let stem = FloeRealSimulatorQualification.fixtureStem
        let file = app.cells.matching(NSPredicate(
            format: "identifier == \"\(stem).pptx, pptx\" || identifier == \"\(stem), pptx\""
        )).firstMatch
        try require(file.waitForExistence(timeout: 10), phase, "Fixture cell missing")
        file.tap()
        let webview = app.webViews.containing(.other, identifier: "Online Editor").firstMatch
        try require(webview.waitForExistence(timeout: 30), phase,
                    "Editor web view did not appear")
        let loading = webview.staticTexts["Loading…"]
        try require(loading.waitForNonExistence(timeout: FloeRealSimulatorQualification.loadTimeout),
                    phase, "Editor did not finish loading")
        return webview
    }

    /// Close from view mode with the real navigation close control and require
    /// the document browser to return. Upstream Lifecycle.closeDocument
    /// assumes read-only mode; callers must leave edit first.
    @MainActor
    func closeDocumentVerified(_ app: XCUIApplication, phase: String) throws {
        let closeButton = app.otherElements["navigation"].buttons.firstMatch
        try require(closeButton.waitForExistence(timeout: 15), phase,
                    "navigation close button not found")
        Lifecycle.closeDocument(app: app)
        try require(app.buttons["Search"].waitForExistence(timeout: 25), phase,
                    "document browser did not appear after close")
    }

    /// Leave edit with a real control: notebookbar "Read mode" when present,
    /// otherwise the "Editing" view-mode dropdown -> "Viewing Mode".
    @MainActor
    func leaveEditMode(_ app: XCUIApplication) throws {
        if let readMode = firstElementWaiting(app, ["Read mode"], timeout: 5) {
            readMode.tap()
        } else {
            guard let editing = firstElementWaiting(
                app, ["Editing", "viewModeDropdownButton"], timeout: 10) else {
                try require(false, "leave-edit",
                            "no Read mode control and no Editing view-mode dropdown found")
                return
            }
            editing.tap()
            guard let viewing = firstElementWaiting(
                app, ["Viewing Mode", "Viewing"], timeout: 10) else {
                try require(false, "leave-edit", "view-mode menu item did not appear")
                return
            }
            viewing.tap()
        }
        // Real read-only state on tablet: the floating Edit document control
        // must reappear once edit mode is left.
        let editControl = app.buttons.matching(
            NSPredicate(format: "label == %@", "Edit document")).firstMatch
        try require(editControl.waitForExistence(timeout: 25), "leave-edit",
                    "Edit document control did not reappear after leaving edit")
    }

    @MainActor
    func testPPTPreviewCloseReopenEditIdleSaveReopen() throws {
        let app = XCUIApplication()
        app.launchArguments = ["-AppleLanguages", "(en-US)", "-AppleLocale", "en_US"]
        app.launch()
        let scenarioStart = Date()
        defer {
            FloeRealSimulatorQualification.receipt["seconds"] =
                Date().timeIntervalSince(scenarioStart)
            attachReceipt()
        }
        do {
            // 1. preview open (iPad starts in read-only view mode)
            _ = try openFixture(app, phase: "preview-open")
            mark("preview-open", true)
            shot("01-preview")

            // 2. rapid close; the two-native-opens failure path starts here.
            try closeDocumentVerified(app, phase: "preview-close")
            mark("preview-close", true)

            // 3. second native open, still view mode
            _ = try openFixture(app, phase: "reopen-before-edit")
            mark("reopen-before-edit", true)

            // 4. enter edit with the real floating control
            if let edit = firstElementWaiting(app, ["Edit document"], timeout: 5) {
                edit.tap()
            }
            let insert = firstElementWaiting(
                app, ["Insert Slide", "New Slide", "Insert Page", "insertpage"], timeout: 60)
            try require(insert != nil, "enter-edit",
                        "Impress edit controls did not appear after tapping Edit document")
            mark("enter-edit", true)
            shot("02-edit")

            // 5. insert a slide and require the real slide count to move to 3.
            insert!.tap()
            let inserted = waitForSlideCount(app, expected: 3, timeout: 30)
            var inventory: [String] = []
            let allButtons = app.descendants(matching: .button)
            if allButtons.firstMatch.waitForExistence(timeout: 5) {
                for index in 0..<min(allButtons.count, 120) {
                    inventory.append(allButtons.element(boundBy: index).label)
                }
            }
            FloeRealSimulatorQualification.receipt["buttonInventory"] = inventory
            try require(inserted, "insert-slide",
                        "slide count did not reach 3 after Insert Slide (status/preview not observed)")
            mark("insert-slide", true)

            // 6. idle 120 s in edit mode, then require the editor is still alive.
            Thread.sleep(forTimeInterval: FloeRealSimulatorQualification.idleSeconds)
            let alive = app.webViews.containing(.other, identifier: "Online Editor").firstMatch.exists
            try require(alive, "idle-120s", "editor web view disappeared during idle")
            mark("idle-120s", true)
            shot("03-idle-120s")

            // 7. explicit save through the real Save control. Completion is
            //    judged by the on-disk persistence gate, not assumed here.
            guard let save = firstElementWaiting(app, ["Save", "save"], timeout: 15) else {
                try require(false, "save", "no Save control found")
                return
            }
            save.tap()
            Thread.sleep(forTimeInterval: 3)
            mark("save", true, "tapped the real Save control; persistence judged by the file gate")

            // 8. leave edit through a real control; required before the
            //    upstream close helper, which assumes read-only mode.
            try leaveEditMode(app)
            mark("leave-edit", true)

            // 9. close from view mode.
            try closeDocumentVerified(app, phase: "close")
            mark("close", true)

            // 10. reopen and confirm the editor loads again.
            _ = try openFixture(app, phase: "reopen")
            mark("reopen", true)
            shot("04-reopen")

            // 11. final close.
            try closeDocumentVerified(app, phase: "close-after-reopen")
            mark("close-after-reopen", true)

            // Receipt self-check: exact coverage, all ok.
            let phases = FloeRealSimulatorQualification.receipt["phases"] as? [[String: Any]] ?? []
            let names = Set(phases.compactMap { $0["phase"] as? String })
            let expected = Set(FloeRealSimulatorQualification.expectedPhases)
            let allOk = phases.allSatisfy { ($0["ok"] as? Bool) == true }
            try require(names == expected && allOk, "coverage",
                        "receipt coverage mismatch: got \(names.sorted())")
        } catch {
            mark("scenario", false, "\(error)")
            shot("99-failure")
            throw error
        }
        app.terminate()
    }
}
'''


def generate(source_dir, output=None):
    source_dir = Path(source_dir).resolve()
    stem = Path(FIXTURE_BASENAME).stem
    phases = ', '.join(f'"{phase}"' for phase in SCENARIO_PHASES)
    content = (SWIFT_TEMPLATE
               .replace('@@FIXTURE_BASENAME@@', FIXTURE_BASENAME)
               .replace('@@FIXTURE_STEM@@', stem)
               .replace('@@IDLE_SECONDS@@', str(IDLE_SECONDS))
               .replace('@@LOAD_TIMEOUT@@', str(int(EDITOR_LOAD_TIMEOUT)))
               .replace('@@RECEIPT_NAME@@', RECEIPT_ATTACHMENT_NAME)
               .replace('@@PHASES@@', phases)
               .replace('@@NATIVE_SEQUENCE@@', SCENARIO_NATIVE_SEQUENCE))
    target = Path(output) if output else (
        source_dir / 'ios/MobileUITests/Tests/FloeRealSimulatorQualification.swift')
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    return {'generated': str(target), 'fixture': FIXTURE_BASENAME,
            'idleSeconds': IDLE_SECONDS, 'phases': list(SCENARIO_PHASES),
            'nativeSequence': SCENARIO_NATIVE_SEQUENCE,
            'receiptAttachment': RECEIPT_ATTACHMENT_NAME,
            'hostKind': 'upstream-mobile-host-only'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source_dir', help='Restored source tree root')
    parser.add_argument('--output', default=None)
    args = parser.parse_args()
    print(json.dumps(generate(args.source_dir, args.output), indent=2))


if __name__ == '__main__':
    main()
