/* Regression fixture for the iOS HULLO forwarding loop lifecycle.
 *
 * Variant under test is selected at compile time:
 *   -DFLOE_VARIANT_ORIGINAL -> loop_original.inc.h  (pinned 27b21dc1 +
 *                              embedding overlay = the shipped Build 237
 *                              source)
 *   -DFLOE_VARIANT_PATCHED  -> loop_patched.inc.h   (+ the
 *                              ios-forwarding-lifecycle overlay)
 *
 * Both loop includes are generated by test_office_forwarding_lifecycle.py
 * via mechanical marker extraction from the staged overlay states; the diff
 * between them is exactly the reviewed patch.
 *
 * REAL code exercised here:
 *   - net/FakeSocket.cpp, pinned 27b21dc1 (compiled unmodified);
 *   - the extracted HULLO forwarding block of the respective variant
 *     (byte-faithful; the three calls forming the two race windows reach the
 *     real implementation through pass-through gates);
 *   - CODocument.send2JS's crash-relevant line `std::string(buffer, length)`.
 *
 * MOCKED (explicitly not real): WKWebView / the JS side (a counted string
 * sink stands in for CoolURLSchemeHandler + evaluateJavaScript), UIKit view
 * controller behavior, COOLWSD/kit internals (the "engine" here is a harness
 * thread speaking the real fake-socket protocol), and LibreOffice. This
 * fixture therefore proves behavior of the app-side forwarding logic only;
 * it is not a device PPT reproduction.
 */

#import <Foundation/Foundation.h>

#include "config.h"

#include "FakeSocket.hpp" // real prototypes for harness-direct calls

#include "common/ProcUtil.hpp"
#include "Log.hpp"
#include "gates.h"

#include <atomic>
#include <cassert>
#include <cstdio>
#include <cstring>
#include <exception>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <unistd.h>
#include <vector>

// The embedding-overlay handshake helper used by the HULLO tail (identical in
// both variants; extracted once, file scope).
#include "extracted/helper.inc.h"

#if defined(FLOE_VARIANT_ORIGINAL)
static const char *kVariant = "original";
#elif defined(FLOE_VARIANT_PATCHED)
static const char *kVariant = "patched";
#else
#error "compile with -DFLOE_VARIANT_ORIGINAL or -DFLOE_VARIANT_PATCHED"
#endif

// Pinned ios/ios.h global: the COOLWSD "public" listening socket.
int coolwsd_server_socket_fd = -1;

// ---------------------------------------------------------------------------
// Mock JS sink (stands in for CoolURLSchemeHandler + WKWebView; counted).

static std::mutex theSinkMutex;
static std::vector<std::string> theDelivered;

static void sinkDeliver(const std::string &message)
{
    std::lock_guard<std::mutex> lock(theSinkMutex);
    theDelivered.push_back(message);
}

static std::vector<std::string> sinkSnapshot()
{
    std::lock_guard<std::mutex> lock(theSinkMutex);
    return theDelivered;
}

static void sinkReset()
{
    std::lock_guard<std::mutex> lock(theSinkMutex);
    theDelivered.clear();
}

// Log shim backing store.
static std::atomic<int> theErrorLogCount(0);

void floeHarnessLogError(const std::string &line)
{
    theErrorLogCount.fetch_add(1);
    fprintf(stderr, "FLOE_LOG_ERR %s\n", line.c_str());
}

int floeHarnessErrorLogCount() { return theErrorLogCount.load(); }
void floeHarnessResetErrorLog() { theErrorLogCount.store(0); }

// ---------------------------------------------------------------------------
// Fixtures mirroring the pinned CODocument / DocumentViewController surface
// used by the extracted block (public ivars, same names).

@interface FloeFixtureDocument : NSObject {
 @public
    int fakeClientFd;
    unsigned appDocId;
    BOOL readOnly;
    NSURL *copyFileURL;
}
@end

@implementation FloeFixtureDocument
// The crash-relevant first line is the verbatim pinned CODocument send2JS
// line (pinned 27b21dc1 ios/Mobile/CODocument.mm:108). The scheme-handler
// queue and the WKWebView evaluation are the mocked sink (counted strings).
- (void)send2JS:(const char *)buffer length:(int)length
{
    std::string message = std::string(buffer, length);
    sinkDeliver(message);
}
@end

@interface FloeFakeMessage : NSObject
@property(nonatomic, copy) NSString *body;
@end

@implementation FloeFakeMessage
@end

@interface FloeFixtureController : NSObject {
 @public
    int closeNotificationPipeForForwardingThread[2];
    BOOL floeClosing;
    BOOL floeClosed;
    BOOL floeForwarderActive;
}
@property(nonatomic, strong) FloeFixtureDocument *document;
- (void)didReceiveHULLO:(FloeFakeMessage *)message;
// Replicates the embedding-overlay bye's observable state transitions, in
// order: floeClosing is set (dismissDocumentViewController's first act) and
// pipe end 0 is closed and reset. UIDocument dismissal and the actual
// document close are out of scope for this harness.
- (void)simulateByePipeClose;
// Harness-only escape hatch for retiring a leaked original-variant forwarder:
// close whatever fd currently sits in pipe end 0 (a duplicate HULLO may have
// overwritten it).
- (void)forceCloseCurrentPipeZero;
// Ownership-flag snapshot under the same monitor the patched loop uses.
- (BOOL)forwarderActiveSnapshot;
@end

@implementation FloeFixtureController

- (instancetype)init
{
    self = [super init];
    if (self) {
        closeNotificationPipeForForwardingThread[0] = -1;
        closeNotificationPipeForForwardingThread[1] = -1;
        floeClosing = NO;
        floeClosed = NO;
        floeForwarderActive = NO;
    }
    return self;
}

- (void)simulateByePipeClose
{
    if (floeClosing || floeClosed)
        return;
    floeClosing = YES;
    if (closeNotificationPipeForForwardingThread[0] >= 0) {
        fakeSocketClose(closeNotificationPipeForForwardingThread[0]);
        closeNotificationPipeForForwardingThread[0] = -1;
    }
}

- (void)forceCloseCurrentPipeZero
{
    if (closeNotificationPipeForForwardingThread[0] >= 0) {
        fakeSocketClose(closeNotificationPipeForForwardingThread[0]);
        closeNotificationPipeForForwardingThread[0] = -1;
    }
}

- (BOOL)forwarderActiveSnapshot
{
    @synchronized (self) {
        return floeForwarderActive;
    }
}

- (void)didReceiveHULLO:(FloeFakeMessage *)message
{
    int rc;
// Rename exactly the three calls that form the two race windows for the
// extracted region only; the loop text flows through the deterministic
// gates while every harness-direct call below reaches the real functions.
#define fakeSocketPoll floe_gate_poll
#define fakeSocketAvailableDataLength floe_gate_available
#define fakeSocketRead floe_gate_read
#if defined(FLOE_VARIANT_ORIGINAL)
#include "extracted/loop_original.inc.h"
#elif defined(FLOE_VARIANT_PATCHED)
#include "extracted/loop_patched.inc.h"
#endif
#undef fakeSocketPoll
#undef fakeSocketAvailableDataLength
#undef fakeSocketRead
}

@end

// ---------------------------------------------------------------------------
// Engine side: a harness thread speaking the real fake-socket protocol.

enum class FdState { Open, Closed };

// fakeSocketAvailableDataLength cannot distinguish "closed" from "idle"
// (both -1); a zero-timeout poll can: a dead endpoint reports POLLNVAL.
static FdState fdState(int fd)
{
    struct pollfd p { fd, POLLIN, 0 };
    fakeSocketPoll(&p, 1, 0);
    return (p.revents & POLLNVAL) ? FdState::Closed : FdState::Open;
}

static bool fdClosed(int fd) { return fdState(fd) == FdState::Closed; }
static bool fdOpen(int fd) { return fdState(fd) == FdState::Open; }

struct Engine {
    int serverFd = -1;
    std::atomic<int> acceptedFd{-1};
    std::atomic<int> stage{0};
    std::string handshake;
    std::thread thread;

    void startListen()
    {
        serverFd = fakeSocketSocket();
        fakeSocketListen(serverFd);
        coolwsd_server_socket_fd = serverFd;
    }

    void run(std::function<void(Engine &)> body)
    {
        thread = std::thread([this, body] { body(*this); });
    }

    void join()
    {
        if (thread.joinable())
            thread.join();
    }
};

static std::string engineReadMessage(int fd)
{
    // fakeSocketRead is non-blocking; poll briefly for the handshake record.
    for (int attempt = 0; attempt < 400; ++attempt) {
        struct pollfd p { fd, POLLIN, 0 };
        if (fakeSocketPoll(&p, 1, 5) > 0 && (p.revents & POLLIN)) {
            char buf[4096];
            const ssize_t n = fakeSocketRead(fd, buf, sizeof(buf));
            if (n > 0)
                return std::string(buf, (size_t)n);
        }
    }
    return std::string();
}

// ---------------------------------------------------------------------------
// Scenario helpers.

static bool waitFor(const std::function<bool()> &predicate, int timeoutMs)
{
    for (int elapsed = 0; elapsed < timeoutMs; elapsed += 5)
        @autoreleasepool {
            if (predicate())
                return true;
            usleep(5000);
        }
    return predicate();
}

static void resultLine(const char *scenario, const char *key, const std::string &value)
{
    printf("FLOE_RESULT {\"scenario\":\"%s\",\"variant\":\"%s\",\"%s\":\"%s\"}\n", scenario, kVariant,
           key, value.c_str());
}

static void resultLong(const char *scenario, const char *key, long value)
{
    printf("FLOE_RESULT {\"scenario\":\"%s\",\"variant\":\"%s\",\"%s\":%ld}\n", scenario, kVariant, key,
           value);
}

static int fail(const char *scenario, const std::string &reason)
{
    resultLine(scenario, "verdict", "FAIL: " + reason);
    return 2;
}

struct Session {
    FloeFixtureController *controller = nil;
    __weak FloeFixtureController *weakController = nil;
    int clientFd = -1;
    Engine engine;

    ~Session() { coolwsd_server_socket_fd = -1; }
};

static std::unique_ptr<Session> startSession(bool withListener)
{
    auto session = std::make_unique<Session>();
    FloeFixtureDocument *document = [FloeFixtureDocument new];
    document->fakeClientFd = fakeSocketSocket();
    document->appDocId = 1;
    document->readOnly = NO;
    document->copyFileURL = [NSURL fileURLWithPath:@"/tmp/floe-harness/ppt/regression.pptx"];
    session->controller = [FloeFixtureController new];
    session->controller.document = document;
    session->weakController = session->controller;
    session->clientFd = document->fakeClientFd;
    if (withListener)
        session->engine.startListen();
    else
        coolwsd_server_socket_fd = fakeSocketSocket(); // valid but not listening
    return session;
}

static void sendHULLO(Session &session)
{
    FloeFakeMessage *message = [FloeFakeMessage new];
    message.body = @"HULLO";
    [session.controller didReceiveHULLO:message];
}

// Engine body shared by most scenarios: accept, read the URL handshake, run
// the scenario-specific action, then wait for stage 1 and close.
static void engineAcceptHandshake(Engine &engine)
{
    const int accepted = fakeSocketAccept4(engine.serverFd);
    engine.acceptedFd.store(accepted);
    engine.handshake = engineReadMessage(accepted);
}

// ---------------------------------------------------------------------------
// Scenarios. Each returns 0 on met expectations, 2 otherwise. Crash scenarios
// simply execute the logic; the runner observes the child's signal.

static int scenario_double_hullo_race(const char *name)
{
    @autoreleasepool {
        floeGateReset();
        sinkReset();
        floeHarnessResetErrorLog();
        auto session = startSession(true);
        session->engine.run([](Engine &engine) {
            engineAcceptHandshake(engine);
            fakeSocketWrite(engine.acceptedFd.load(), "tile A", 6);
            while (engine.stage.load() == 0)
                usleep(1000);
            fakeSocketClose(engine.acceptedFd.load());
        });
        floeGateArm("after_poll");
        sendHULLO(*session);
        if (floeGateWaitEntered("after_poll", 5000) != 0)
            return fail(name, "forwarder did not reach the poll gate");
        // The second HULLO on the same live document: tdf#122543 shape.
        sendHULLO(*session);
        usleep(150 * 1000); // let a second consumer (original) drain the record
        floeGateRelease("after_poll");
        // ORIGINAL dies here: the held consumer observes available == -1 and
        // constructs std::vector<char>(-1). PATCHED refused the duplicate
        // HULLO (ownership flag), so the single consumer delivers the record.
        session->engine.stage.store(1);
        session->engine.join();
        if (!waitFor([&] { return sinkSnapshot().size() == 1; }, 5000))
            return fail(name, "record was not delivered exactly once");
        if (sinkSnapshot()[0] != "tile A")
            return fail(name, "delivered payload mismatch");
        const int clientFd = session->clientFd;
        const int pipeFd = session->controller->closeNotificationPipeForForwardingThread[1];
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "forwarder leaked after EOF");
        if (floeHarnessErrorLogCount() < 1)
            return fail(name, "patched variant must log the refused duplicate HULLO");
        if (!fdClosed(clientFd) || !fdClosed(pipeFd))
            return fail(name, "patched retirement must close the client fd and the pipe end");
        resultLine(name, "verdict", "pass");
        resultLong(name, "errorLogs", floeHarnessErrorLogCount());
        return 0;
    }
}

// Primary-review case: duplicate HULLO after BYE, while the first forwarder
// is still inside its poll window (pipe end 0 already closed and reset).
static int scenario_after_bye_race(const char *name)
{
    @autoreleasepool {
        floeGateReset();
        sinkReset();
        floeHarnessResetErrorLog();
        auto session = startSession(true);
        session->engine.run([](Engine &engine) {
            engineAcceptHandshake(engine);
            fakeSocketWrite(engine.acceptedFd.load(), "tile A", 6);
            while (engine.stage.load() == 0)
                usleep(1000);
            fakeSocketClose(engine.acceptedFd.load());
        });
        floeGateArm("after_poll");
        sendHULLO(*session);
        if (floeGateWaitEntered("after_poll", 5000) != 0)
            return fail(name, "forwarder did not reach the poll gate");
        // BYE closes and resets pipe end 0 while consumer A is held inside
        // its poll window; the duplicate HULLO arrives in that window.
        [session->controller simulateByePipeClose];
        sendHULLO(*session);
        usleep(150 * 1000); // original: second forwarder drains the record
        floeGateRelease("after_poll");
        // ORIGINAL: A's pipe-fd check admitted the second consumer (pipe end
        // was already reset); A now observes available == -1 and dies from
        // std::vector<char>(-1). PATCHED: the closing gate refused the
        // duplicate; A drains the record and retires through the pipe event.
        session->engine.stage.store(1);
        session->engine.join();
        if (!waitFor([&] { return sinkSnapshot().size() == 1; }, 5000))
            return fail(name, "patched must deliver the polled record exactly once");
        const int clientFd = session->clientFd;
        const int pipeFd = session->controller->closeNotificationPipeForForwardingThread[1];
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "forwarder leaked after the BYE-window retirement");
        if (floeHarnessErrorLogCount() < 1)
            return fail(name, "patched must log the refused post-BYE HULLO");
        if (!fdClosed(clientFd) || !fdClosed(pipeFd))
            return fail(name, "patched retirement must close both fds");
        resultLine(name, "verdict", "pass");
        return 0;
    }
}

// Same window, ungated: on the original the duplicate HULLO leaks a second
// forwarder that spins on POLLNVAL forever (the first retired cleanly via
// the pipe branch); on the patched variant no second consumer ever exists.
static int scenario_after_bye_second_forwarder(const char *name)
{
    @autoreleasepool {
        floeGateReset();
        sinkReset();
        floeHarnessResetErrorLog();
        auto session = startSession(true);
        session->engine.run([](Engine &engine) {
            engineAcceptHandshake(engine);
            while (engine.stage.load() == 0)
                usleep(1000);
            fakeSocketClose(engine.acceptedFd.load());
        });
        sendHULLO(*session);
        if (!waitFor([&] { return session->engine.acceptedFd.load() >= 0; }, 5000))
            return fail(name, "engine accept did not complete");
        usleep(100 * 1000);
        [session->controller simulateByePipeClose];
        // Deterministic: the first forwarder has retired (it closed the
        // client fd in both variants) before the duplicate HULLO arrives.
        if (!waitFor([&] { return fdClosed(session->clientFd); }, 5000))
            return fail(name, "first forwarder did not retire via the pipe branch");
        sendHULLO(*session); // duplicate in the post-BYE window
        usleep(200 * 1000);
#if defined(FLOE_VARIANT_ORIGINAL)
        // The original admitted the duplicate: a second forwarder now spins
        // on POLLNVAL (the first forwarder closed the client fd) and keeps
        // the controller alive forever.
        const long polls = floeGatePollCount();
        usleep(200 * 1000);
        if (floeGatePollCount() <= polls)
            return fail(name, "original must spin a leaked second forwarder on POLLNVAL");
        if (session->weakController == nil)
            return fail(name, "original must leak the second forwarder");
        [session->controller forceCloseCurrentPipeZero]; // harness cleanup of the leak
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "leaked original forwarder did not retire on forced pipe close");
        resultLine(name, "verdict", "pass");
        resultLine(name, "behavior", "duplicate HULLO after BYE leaked a second forwarder spinning on POLLNVAL");
#else
        const long polls = floeGatePollCount();
        usleep(200 * 1000);
        if (floeGatePollCount() != polls)
            return fail(name, "patched must not start a second forwarder after BYE");
        if (floeHarnessErrorLogCount() < 1)
            return fail(name, "patched must log the refused post-BYE HULLO");
        const int clientFd = session->clientFd;
        const int pipeFd = session->controller->closeNotificationPipeForForwardingThread[1];
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "patched forwarder leaked");
        if (!fdClosed(clientFd) || !fdClosed(pipeFd))
            return fail(name, "patched retirement must close both fds");
        resultLine(name, "verdict", "pass");
        resultLine(name, "behavior", "post-BYE HULLO refused; single forwarder retired via pipe");
#endif
        session->engine.stage.store(1);
        session->engine.join();
        return 0;
    }
}

static int scenario_read_race(const char *name)
{
    @autoreleasepool {
        floeGateReset();
        sinkReset();
        floeHarnessResetErrorLog();
        auto session = startSession(true);
        session->engine.run([](Engine &engine) {
            engineAcceptHandshake(engine);
            fakeSocketWrite(engine.acceptedFd.load(), "tile B", 6);
            while (engine.stage.load() == 0)
                usleep(1000);
            fakeSocketClose(engine.acceptedFd.load());
        });
        floeGateArm("after_available");
        sendHULLO(*session);
        if (floeGateWaitEntered("after_available", 5000) != 0)
            return fail(name, "forwarder did not reach the available-length gate");
        // A second consumer draining the same record between the two calls:
        // the harness performs exactly the read a duplicate forwarder would.
        char drain[64];
        const ssize_t drained = fakeSocketRead(session->clientFd, drain, sizeof(drain));
        if (drained != 6)
            return fail(name, "second consumer could not drain the record");
        floeGateRelease("after_available");
        // ORIGINAL dies here: read returns -1 and send2JS builds
        // std::string(buffer, -1). PATCHED logs and retires.
        session->engine.stage.store(1);
        session->engine.join();
        usleep(100 * 1000);
        const int clientFd = session->clientFd;
        const int pipeFd = session->controller->closeNotificationPipeForForwardingThread[1];
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "forwarder leaked after the failed read");
        if (floeHarnessErrorLogCount() < 1)
            return fail(name, "patched variant must log the failed read");
        if (!sinkSnapshot().empty())
            return fail(name, "no delivery may follow a failed read");
        if (!fdClosed(clientFd) || !fdClosed(pipeFd))
            return fail(name, "patched retirement must close both fds");
        resultLine(name, "verdict", "pass");
        resultLong(name, "errorLogs", floeHarnessErrorLogCount());
        return 0;
    }
}

static int scenario_peer_shutdown(const char *name)
{
    @autoreleasepool {
        floeGateReset();
        sinkReset();
        floeHarnessResetErrorLog();
        auto session = startSession(true);
        session->engine.run([](Engine &engine) {
            engineAcceptHandshake(engine);
            fakeSocketShutdown(engine.acceptedFd.load());
            while (engine.stage.load() == 0)
                usleep(1000);
            fakeSocketClose(engine.acceptedFd.load());
        });
        sendHULLO(*session);
        if (!waitFor([&] { return session->engine.acceptedFd.load() >= 0; }, 5000))
            return fail(name, "engine accept did not complete");
        usleep(300 * 1000); // observation window
        const long polls = floeGatePollCount();
        resultLong(name, "pollCallsIn300ms", polls);
#if defined(FLOE_VARIANT_ORIGINAL)
        // Equality revents checks skip POLLIN|POLLHUP: the original spins and
        // the forwarder leaks until the close pipe fires.
        if (polls < 50)
            return fail(name, "original must spin on POLLIN|POLLHUP (spin not observed)");
        [session->controller simulateByePipeClose];
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "original forwarder did not retire on pipe close");
        if (!fdClosed(session->clientFd))
            return fail(name, "original pipe retirement closes the client fd (parity evidence)");
        resultLine(name, "verdict", "pass");
        resultLine(name, "behavior", "spun on POLLIN|POLLHUP; retired only via pipe close");
#else
        if (polls > 10)
            return fail(name, "patched must retire promptly on peer shutdown");
        const int clientFd = session->clientFd;
        const int pipeFd = session->controller->closeNotificationPipeForForwardingThread[1];
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "patched forwarder leaked after peer shutdown");
        if (!fdClosed(clientFd) || !fdClosed(pipeFd))
            return fail(name, "patched EOF retirement must close both fds");
        resultLine(name, "verdict", "pass");
        resultLine(name, "behavior", "observed POLLHUP, clean EOF retire");
#endif
        session->engine.stage.store(1);
        session->engine.join();
        return 0;
    }
}

static int scenario_normal_delivery(const char *name)
{
    @autoreleasepool {
        floeGateReset();
        sinkReset();
        floeHarnessResetErrorLog();
        auto session = startSession(true);
        session->engine.run([](Engine &engine) {
            engineAcceptHandshake(engine);
            fakeSocketWrite(engine.acceptedFd.load(), "status:", 7);
            fakeSocketWrite(engine.acceptedFd.load(), "tile:1", 6);
            fakeSocketWrite(engine.acceptedFd.load(), "tile:2", 6);
            fakeSocketClose(engine.acceptedFd.load());
        });
        sendHULLO(*session);
        if (!waitFor([&] { return sinkSnapshot().size() == 3; }, 5000))
            return fail(name, "did not deliver all three records");
        const std::vector<std::string> delivered = sinkSnapshot();
        if (delivered[0] != "status:" || delivered[1] != "tile:1" || delivered[2] != "tile:2")
            return fail(name, "delivery order/content mismatch");
        session->engine.join();
        const int clientFd = session->clientFd;
        const int pipeFd = session->controller->closeNotificationPipeForForwardingThread[1];
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "forwarder leaked after clean EOF");
        if (floeHarnessErrorLogCount() != 0)
            return fail(name, "happy path must not log errors");
        if (session->engine.handshake.find("regression.pptx") == std::string::npos)
            return fail(name, "handshake URL did not reach the engine");
        // Collateral invariant: app-side retirement must never touch fds it
        // does not own (the listening socket outlives the session).
        if (!fdOpen(session->engine.serverFd))
            return fail(name, "app-side retirement closed the listening socket");
#if defined(FLOE_VARIANT_ORIGINAL)
        // The original EOF path (n == 0) leaks both fds.
        if (!fdOpen(clientFd) || !fdOpen(pipeFd))
            return fail(name, "original EOF path must leak both fds (known defect)");
        resultLine(name, "behavior", "delivered 3/3; EOF return leaked client fd and pipe end");
#else
        if (!fdClosed(clientFd) || !fdClosed(pipeFd))
            return fail(name, "patched EOF retirement must close both fds");
        resultLine(name, "behavior", "delivered 3/3; EOF retirement closed both fds");
#endif
        resultLine(name, "verdict", "pass");
        resultLine(name, "handshake", session->engine.handshake);
        return 0;
    }
}

static int scenario_close_notification(const char *name)
{
    @autoreleasepool {
        floeGateReset();
        sinkReset();
        floeHarnessResetErrorLog();
        auto session = startSession(true);
        session->engine.run([](Engine &engine) {
            engineAcceptHandshake(engine);
            while (engine.stage.load() == 0)
                usleep(1000);
            fakeSocketClose(engine.acceptedFd.load());
        });
        sendHULLO(*session);
        if (!waitFor([&] { return session->engine.acceptedFd.load() >= 0; }, 5000))
            return fail(name, "engine accept did not complete");
        usleep(100 * 1000);
        const int clientFd = session->clientFd;
        const int pipeFd = session->controller->closeNotificationPipeForForwardingThread[1];
        [session->controller simulateByePipeClose];
        if (!waitFor([&] { return fdClosed(clientFd); }, 5000))
            return fail(name, "forwarder did not close the client socket");
        if (!waitFor([&] { return fdClosed(pipeFd); }, 5000))
            return fail(name, "forwarder did not close the pipe end");
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "forwarder leaked after the close notification");
        if (floeHarnessErrorLogCount() != 0)
            return fail(name, "close notification must not log errors");
        session->engine.stage.store(1);
        session->engine.join();
        resultLine(name, "verdict", "pass");
        return 0;
    }
}

static int scenario_duplicate_hullo_single_delivery(const char *name)
{
    @autoreleasepool {
        floeGateReset();
        sinkReset();
        floeHarnessResetErrorLog();
        auto session = startSession(true);
        session->engine.run([](Engine &engine) {
            engineAcceptHandshake(engine);
            fakeSocketWrite(engine.acceptedFd.load(), "only tile", 9);
            while (engine.stage.load() == 0)
                usleep(1000);
            fakeSocketClose(engine.acceptedFd.load());
        });
        sendHULLO(*session);
        sendHULLO(*session); // duplicate; no race gates involved
        if (!waitFor([&] { return sinkSnapshot().size() == 1; }, 5000))
            return fail(name, "record was not delivered");
        usleep(200 * 1000);
        if (sinkSnapshot().size() != 1 || sinkSnapshot()[0] != "only tile")
            return fail(name, "record delivered more than once");
        session->engine.stage.store(1);
        session->engine.join();
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "forwarder leaked after EOF");
        if (floeHarnessErrorLogCount() < 1)
            return fail(name, "duplicate HULLO must be logged");
        resultLine(name, "verdict", "pass");
        return 0;
    }
}

static int scenario_connect_failure(const char *name)
{
    @autoreleasepool {
        floeGateReset();
        sinkReset();
        floeHarnessResetErrorLog();
        auto session = startSession(false); // valid server fd, never listening
        sendHULLO(*session);
        usleep(200 * 1000);
#if defined(FLOE_VARIANT_ORIGINAL)
        // NDEBUG: the failed connect is ignored, a forwarder starts on the
        // unconnected socket and blocks in poll until the close pipe fires.
        [session->controller simulateByePipeClose];
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "original forwarder did not retire on pipe close");
        resultLine(name, "verdict", "pass");
        resultLine(name, "behavior", "forwarder blocked on unconnected socket until pipe close");
#else
        if (floeHarnessErrorLogCount() < 1)
            return fail(name, "patched must log the failed connect");
        if (floeGatePollCount() != 0)
            return fail(name, "patched must not start a forwarder on a dead socket");
        if ([session->controller forwarderActiveSnapshot])
            return fail(name, "failed connect must clear the ownership flag for a later retry");
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "patched retained a forwarder on a dead socket");
        resultLine(name, "verdict", "pass");
        resultLine(name, "behavior", "no forwarder on failed connect");
        // The ownership flag is not latched: once the server listens, a
        // later HULLO connects and forwards normally.
        FloeFixtureDocument *document = [FloeFixtureDocument new];
        document->fakeClientFd = session->clientFd; // same client socket, never connected
        document->appDocId = 1;
        document->readOnly = NO;
        document->copyFileURL = [NSURL fileURLWithPath:@"/tmp/floe-harness/ppt/regression.pptx"];
        FloeFixtureController *controller = [FloeFixtureController new];
        controller.document = document;
        __weak FloeFixtureController *weakRetry = controller;
        Engine engine;
        engine.startListen();
        engine.run([](Engine &eng) {
            engineAcceptHandshake(eng);
            fakeSocketWrite(eng.acceptedFd.load(), "retry tile", 10);
            fakeSocketClose(eng.acceptedFd.load());
        });
        FloeFakeMessage *message = [FloeFakeMessage new];
        message.body = @"HULLO";
        [controller didReceiveHULLO:message];
        if (!waitFor([&] { return sinkSnapshot().size() == 1; }, 5000))
            return fail(name, "retry HULLO did not deliver");
        if (sinkSnapshot()[0] != "retry tile")
            return fail(name, "retry payload mismatch");
        engine.join();
        controller = nil;
        if (!waitFor([&] { return weakRetry == nil; }, 5000))
            return fail(name, "retry forwarder leaked");
        resultLine(name, "retry", "later HULLO after a failed connect delivers and retires cleanly");
#endif
        return 0;
    }
}

static int scenario_invalid_client_fd(const char *name)
{
    @autoreleasepool {
        floeGateReset();
        sinkReset();
        floeHarnessResetErrorLog();
        auto session = startSession(true);
        session->engine.run([](Engine &engine) {
            engineAcceptHandshake(engine);
            while (engine.stage.load() == 0)
                usleep(1000);
            fakeSocketClose(engine.acceptedFd.load());
        });
        sendHULLO(*session);
        if (!waitFor([&] { return session->engine.acceptedFd.load() >= 0; }, 5000))
            return fail(name, "engine accept did not complete");
        fakeSocketClose(session->clientFd); // defensive: fd gone under the forwarder
        usleep(200 * 1000);
#if defined(FLOE_VARIANT_ORIGINAL)
        // POLLNVAL fails both equality checks: the original spins until the
        // pipe close retires it.
        if (floeGatePollCount() < 5)
            return fail(name, "original must spin on POLLNVAL");
        [session->controller simulateByePipeClose];
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "original forwarder did not retire on pipe close");
        resultLine(name, "verdict", "pass");
        resultLine(name, "behavior", "spun on POLLNVAL; retired only via pipe close");
#else
        const int pipeFd = session->controller->closeNotificationPipeForForwardingThread[1];
        session->controller = nil;
        if (!waitFor([&] { return session->weakController == nil; }, 5000))
            return fail(name, "patched forwarder leaked after POLLNVAL");
        if (floeHarnessErrorLogCount() < 1)
            return fail(name, "patched must log the invalid socket");
        if (!fdClosed(pipeFd))
            return fail(name, "patched POLLNVAL retirement must close the pipe end");
        resultLine(name, "verdict", "pass");
        resultLine(name, "behavior", "clean retire on POLLNVAL");
#endif
        session->engine.stage.store(1);
        session->engine.join();
        return 0;
    }
}

// ---------------------------------------------------------------------------

static void installTerminateMarker()
{
    std::set_terminate([] {
        const char *type = "unknown";
        try {
            if (std::exception_ptr current = std::current_exception())
                std::rethrow_exception(current);
        } catch (const std::length_error &) {
            type = "std::length_error";
        } catch (const std::exception &) {
            type = "std::exception";
        } catch (...) {
        }
        fprintf(stderr, "FLOE_TERMINATE type=%s\n", type);
        fflush(stderr);
        abort();
    });
}

int main(int argc, char **argv)
{
    std::string scenario;
    for (int i = 1; i < argc; i++) {
        if (std::strcmp(argv[i], "--scenario") == 0 && i + 1 < argc)
            scenario = argv[++i];
    }
    installTerminateMarker();
    printf("FLOE_RESULT {\"variant\":\"%s\",\"scenario\":\"%s\",\"event\":\"start\"}\n", kVariant,
           scenario.c_str());
    fflush(stdout);
    if (scenario == "double_hullo_race")
        return scenario_double_hullo_race("double_hullo_race");
    if (scenario == "after_bye_race")
        return scenario_after_bye_race("after_bye_race");
    if (scenario == "after_bye_second_forwarder")
        return scenario_after_bye_second_forwarder("after_bye_second_forwarder");
    if (scenario == "read_race")
        return scenario_read_race("read_race");
    if (scenario == "peer_shutdown")
        return scenario_peer_shutdown("peer_shutdown");
    if (scenario == "normal_delivery")
        return scenario_normal_delivery("normal_delivery");
    if (scenario == "close_notification")
        return scenario_close_notification("close_notification");
    if (scenario == "duplicate_hullo_single_delivery")
        return scenario_duplicate_hullo_single_delivery("duplicate_hullo_single_delivery");
    if (scenario == "connect_failure")
        return scenario_connect_failure("connect_failure");
    if (scenario == "invalid_client_fd")
        return scenario_invalid_client_fd("invalid_client_fd");
    fprintf(stderr, "unknown scenario: %s\n", scenario.c_str());
    return 64;
}
